/**
 * The editor chrome's glyph set.
 *
 * GENERATED by `tools/build-icons.mjs` — do not hand-edit. To swap a glyph,
 * change the mapping in that script and re-run it. Sources, in order of
 * preference: the design foundations kit (`tools/icons/foundations`, 21
 * drawings) for every role the kit has a glyph for; Lucide 1.46.0
 * (https://lucide.dev/icons, ISC) for the editor's own subjects; and a native
 * lattice family authored in the script.
 *
 * Every glyph sits on one 24x24 grid, and four things follow, each of which
 * used to be the opposite here:
 *
 *   - ONE drawing per glyph, with a fill painted over it rather than a second
 *     drawing. Lucide ships no filled counterparts, and flooding an outline
 *     with `currentColor` reads only for a closed silhouette — but every mark a
 *     TOGGLE in this chrome draws is closed, so the pointer, the bubble and the
 *     layer stack all fill correctly from their own paths and cannot drift in
 *     size from the outline they replace. A row or a tab that reports itself
 *     `aria-selected` still gets the heavier stroke from the stylesheet (see
 *     `css/icons.ts`), because a list has its neighbours on screen to be
 *     compared against and a lone toolbar button does not.
 *
 *   - A `filled` array, on the few glyphs a flood cannot serve. A mark made
 *     only of open runs has no area to flood — `SlidersHorizontal` came out
 *     identical in both states — so those carry an authored counterpart, held
 *     by the generator to the same ink extent as their outline.
 *
 *   - NO per-glyph window. Nothing is re-fitted by widening its viewBox: that
 *     scales a stroke along with the drawing and lands it under weight, trading
 *     a size error for a weight error. The extents are deliberately uneven — a
 *     chevron inks 12 of the grid and a layer stack 20 — because that is
 *     each source's own optical sizing.
 *
 *   - ONE stroke width, the kit's 2, at every size. The kit's filled glyphs
 *     carry that weight baked into their outlines, so a stroke compensated per
 *     size would split the family at the small rungs. See `STROKE_FOR_SIZE`.
 */

export type IconNode = [
  tag: string,
  attrs: Record<string, string | number>,
  children?: IconNode[],
]

/**
 * One glyph: its shapes, on the shared 24 grid. A shape with `stroke: none` is
 * a fill whose weight is its outline; every other shape strokes at the root's
 * width.
 *
 * `filled` is the counterpart drawn for the marks a flood cannot express — see
 * the header. Absent, which is the usual case, the filled weight paints the
 * same shapes with `currentColor`, so the two states cannot be different marks.
 */
export interface IconData {
  shapes: IconNode[]
  filled?: IconNode[]
}

/**
 * Which weight a glyph is asked for.
 *
 * `auto` is the outline, and lets the stylesheet add the extra stroke when the
 * control reports itself selected in a list of its peers — which is how "on
 * means heavier" stays one rule rather than 80 call sites.
 *
 * `filled` is what a TOGGLE asks for while it is on. A stroke half a unit
 * heavier is a relative signal: legible beside the same glyph in its off state,
 * and unreadable on a button sitting on its own, which is exactly the case a
 * mode indicator has to answer. Solid or hollow needs nothing to compare
 * against.
 */
export type IconWeight = "outline" | "filled" | "auto"

/**
 * The only sizes a glyph may be drawn at: the kit's six icon roles in
 * `tokens.icon` — marker 12, inline 14, action 16, chrome 18, header 20,
 * feature 24.
 *
 * A union rather than `number`, so a size off the ramp fails to compile instead
 * of shipping. The set drifted to seven sizes once — 10, 12, 13, 14, 16, 18 and
 * 20, each added at one call site by someone reaching for the value that looked
 * right next to the text beside it. Nothing caught it, because every one of
 * those calls was locally reasonable.
 *
 * Call sites should pass `tokens.icon.action` and friends rather than the number,
 * which is what makes the ramp readable at the point of use; this type is the
 * backstop for the ones that do not.
 */
export type IconSize = 12 | 14 | 16 | 18 | 20 | 24

/**
 * The stroke each rung wears, in grid units: the kit's 2 at every rung.
 *
 * It used to be compensated per size, heavier on the small rungs. Two things
 * retired that. The kit's filled glyphs — chevron-down, x, copy, arrow-up —
 * carry a 2-unit weight baked into their outlines that no attribute can
 * thicken, so compensating the stroked half would split the set at exactly
 * the rungs where the two halves sit side by side. And the rung that needed
 * rescuing is gone: at the kit's floor of 12px, 2 units is exactly 1 CSS pixel,
 * two whole device pixels at 2x. Rendered thickness rises 1.0 to 2.0px across
 * the ramp — the same mark enlarged.
 *
 * `tools/build-icons.mjs` measures every stroked shape's clearance inside the
 * grid and fails the build if the heaviest stroke that renders would clip one.
 */
const STROKE_FOR_SIZE: Record<IconSize, number> = {
  12: 2,
  14: 2,
  16: 2,
  18: 2,
  20: 2,
  24: 2,
}

/**
 * The stroke width, published as a custom property the stylesheet can build on.
 *
 * Written ALONGSIDE the `stroke-width` attribute rather than instead of it. The
 * attribute is the value that is always right, including with no stylesheet at
 * all; the property is what lets one CSS rule say "pressed is half a unit
 * heavier" without knowing which rung the glyph was drawn at.
 */
export const ICON_STROKE_VARIABLE = "--de-icon-stroke"

/**
 * What marks an `<svg>` as one of OURS.
 *
 * The state rule in `css/icons.ts` leans on the custom property above, and
 * without this it would also reach two kinds of `<svg>` it has no business
 * restyling: the host's own icons, which `drawHostIcon` renders inside the
 * inspector exactly as their author drew them, and any `<svg>` the app being
 * edited happens to place inside a selected row. Both would pick up the
 * property's fallback and get re-weighted on selection — the editor quietly
 * redrawing someone else's artwork.
 */
export const ICON_MARKER_ATTRIBUTE = "data-de-glyph"

const ICONS = {
  "AlignCenterHorizontal": {
    // native — inks 18.0x16.5 of 24
    shapes: [
    [
      "rect",
      {
        "x": 3,
        "y": 10.5,
        "width": 18,
        "height": 1.5,
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    [
      "rect",
      {
        "x": 7.5,
        "y": 3,
        "width": 3,
        "height": 16.5,
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    [
      "rect",
      {
        "x": 13.5,
        "y": 6,
        "width": 3,
        "height": 10.5,
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    ],
  },
  "AlignCenterVertical": {
    // native — inks 16.5x18.0 of 24
    shapes: [
    [
      "rect",
      {
        "x": 10.5,
        "y": 3,
        "width": 1.5,
        "height": 18,
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    [
      "rect",
      {
        "x": 3,
        "y": 7.5,
        "width": 16.5,
        "height": 3,
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    [
      "rect",
      {
        "x": 6,
        "y": 13.5,
        "width": 10.5,
        "height": 3,
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    ],
  },
  "AlignEndHorizontal": {
    // native — inks 18.0x18.0 of 24
    shapes: [
    [
      "rect",
      {
        "x": 3,
        "y": 19.5,
        "width": 18,
        "height": 1.5,
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    [
      "rect",
      {
        "x": 7.5,
        "y": 3,
        "width": 3,
        "height": 13.5,
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    [
      "rect",
      {
        "x": 13.5,
        "y": 9,
        "width": 3,
        "height": 7.5,
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    ],
  },
  "AlignEndVertical": {
    // native — inks 18.0x18.0 of 24
    shapes: [
    [
      "rect",
      {
        "x": 19.5,
        "y": 3,
        "width": 1.5,
        "height": 18,
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    [
      "rect",
      {
        "x": 3,
        "y": 7.5,
        "width": 13.5,
        "height": 3,
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    [
      "rect",
      {
        "x": 9,
        "y": 13.5,
        "width": 7.5,
        "height": 3,
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    ],
  },
  "AlignStartHorizontal": {
    // native — inks 18.0x18.0 of 24
    shapes: [
    [
      "rect",
      {
        "x": 3,
        "y": 3,
        "width": 18,
        "height": 1.5,
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    [
      "rect",
      {
        "x": 7.5,
        "y": 7.5,
        "width": 3,
        "height": 13.5,
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    [
      "rect",
      {
        "x": 13.5,
        "y": 7.5,
        "width": 3,
        "height": 7.5,
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    ],
  },
  "AlignStartVertical": {
    // native — inks 18.0x18.0 of 24
    shapes: [
    [
      "rect",
      {
        "x": 3,
        "y": 3,
        "width": 1.5,
        "height": 18,
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    [
      "rect",
      {
        "x": 7.5,
        "y": 7.5,
        "width": 13.5,
        "height": 3,
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    [
      "rect",
      {
        "x": 7.5,
        "y": 13.5,
        "width": 7.5,
        "height": 3,
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    ],
  },
  "ArrangeBack": {
    // native — inks 18.0x18.0 of 24
    shapes: [
    [
      "rect",
      {
        "x": 3,
        "y": 19.5,
        "width": 18,
        "height": 1.5,
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    [
      "rect",
      {
        "x": 10.5,
        "y": 3,
        "width": 1.5,
        "height": 14.25,
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    [
      "path",
      {
        "d": "M6.75 12.75L11.25 17.25L15.75 12.75L15.75 10.649999999999999L11.25 15.149999999999999L6.75 10.649999999999999z",
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    ],
  },
  "ArrangeBackward": {
    // native — inks 9.0x16.5 of 24
    shapes: [
    [
      "rect",
      {
        "x": 10.5,
        "y": 3,
        "width": 1.5,
        "height": 16.5,
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    [
      "path",
      {
        "d": "M6.75 15L11.25 19.5L15.75 15L15.75 12.899999999999999L11.25 17.4L6.75 12.899999999999999z",
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    ],
  },
  "ArrangeForward": {
    // native — inks 9.0x16.5 of 24
    shapes: [
    [
      "rect",
      {
        "x": 10.5,
        "y": 4.5,
        "width": 1.5,
        "height": 16.5,
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    [
      "path",
      {
        "d": "M6.75 9L11.25 4.5L15.75 9L15.75 11.100000000000001L11.25 6.6000000000000005L6.75 11.100000000000001z",
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    ],
  },
  "ArrangeFront": {
    // native — inks 18.0x18.0 of 24
    shapes: [
    [
      "rect",
      {
        "x": 3,
        "y": 3,
        "width": 18,
        "height": 1.5,
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    [
      "rect",
      {
        "x": 10.5,
        "y": 6.75,
        "width": 1.5,
        "height": 14.25,
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    [
      "path",
      {
        "d": "M6.75 11.25L11.25 6.75L15.75 11.25L15.75 13.350000000000001L11.25 8.850000000000001L6.75 13.350000000000001z",
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    ],
  },
  "ArrowDown": {
    // foundations/arrow-up — inks 16.0x22.0 of 24
    shapes: [
    [
      "path",
      {
        "d": "M19.707 15.707L12.707 22.707A0.999 0.999 0 0 1 11.617 22.923A0.998 0.998 0 0 1 11.292 22.706L4.292 15.707A1 1 0 1 1 5.707 14.293L11 19.586L11 2A1 1 0 1 1 13 2L13 19.586L18.293 14.293A0.997 0.997 0 0 1 19.707 14.293A1 1 0 0 1 19.707 15.707z",
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    ],
  },
  "ArrowDownToLine": {
    // lucide/ArrowDownToLine — inks 14.0x18.0 of 24
    shapes: [
    [
      "path",
      {
        "d": "M12 17V3",
      },
    ],
    [
      "path",
      {
        "d": "m6 11 6 6 6-6",
      },
    ],
    [
      "path",
      {
        "d": "M19 21H5",
      },
    ],
    ],
  },
  "ArrowRight": {
    // foundations/arrow-right — inks 22.0x16.0 of 24
    shapes: [
    [
      "path",
      {
        "d": "M22.923 12.382a1.001 1.001 0 0 0-.216-1.09l-7-6.999a1 1 0 1 0-1.414 1.414L19.586 11H2a1 1 0 1 0 0 2h17.586l-5.293 5.293a1 1 0 1 0 1.414 1.414l7-7a.999.999 0 0 0 .216-.325z",
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    ],
  },
  "ArrowUp": {
    // foundations/arrow-up — inks 16.0x22.0 of 24
    shapes: [
    [
      "path",
      {
        "d": "m19.707 8.293-7-7a.999.999 0 0 0-1.09-.216.998.998 0 0 0-.325.217l-7 6.999a1 1 0 1 0 1.415 1.414L11 4.414V22a1 1 0 1 0 2 0V4.414l5.293 5.293a.997.997 0 0 0 1.414 0 1 1 0 0 0 0-1.414z",
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    ],
  },
  "ArrowUpToLine": {
    // lucide/ArrowUpToLine — inks 14.0x18.0 of 24
    shapes: [
    [
      "path",
      {
        "d": "M5 3h14",
      },
    ],
    [
      "path",
      {
        "d": "m18 13-6-6-6 6",
      },
    ],
    [
      "path",
      {
        "d": "M12 7v14",
      },
    ],
    ],
  },
  "Ban": {
    // lucide/Ban — inks 20.0x20.0 of 24
    shapes: [
    [
      "circle",
      {
        "cx": "12",
        "cy": "12",
        "r": "10",
      },
    ],
    [
      "path",
      {
        "d": "M4.929 4.929 19.07 19.071",
      },
    ],
    ],
  },
  "Check": {
    // foundations/check — inks 20.0x13.0 of 24
    shapes: [
    [
      "path",
      {
        "d": "M22 5 9.002 17.998 2.005 11.004",
      },
    ],
    ],
  },
  "ChevronDown": {
    // foundations/chevron-down — inks 20.0x11.0 of 24
    shapes: [
    [
      "path",
      {
        "d": "M12 17.502a1 1 0 0 1-.707-.293l-9-9.004a1 1 0 0 1 1.414-1.414L12 15.087l8.293-8.296a1 1 0 0 1 1.414 1.414l-9 9.004a1 1 0 0 1-.707.293z",
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    ],
  },
  "ChevronRight": {
    // foundations/chevron-right — inks 9.0x18.0 of 24
    shapes: [
    [
      "path",
      {
        "d": "M8 3 17.004 12 8 21",
      },
    ],
    ],
  },
  "ChevronsDownUp": {
    // lucide/ChevronsDownUp — inks 10.0x16.0 of 24
    shapes: [
    [
      "path",
      {
        "d": "m7 20 5-5 5 5",
      },
    ],
    [
      "path",
      {
        "d": "m7 4 5 5 5-5",
      },
    ],
    ],
  },
  "ChevronsUpDown": {
    // lucide/ChevronsUpDown — inks 10.0x16.0 of 24
    shapes: [
    [
      "path",
      {
        "d": "m7 15 5 5 5-5",
      },
    ],
    [
      "path",
      {
        "d": "m7 9 5-5 5 5",
      },
    ],
    ],
  },
  "Circle": {
    // lucide/Circle — inks 20.0x20.0 of 24
    shapes: [
    [
      "circle",
      {
        "cx": "12",
        "cy": "12",
        "r": "10",
      },
    ],
    ],
  },
  "Code": {
    // foundations/code-2 — inks 20.0x16.0 of 24
    shapes: [
    [
      "path",
      {
        "d": "m18 16 4-4-4-4",
      },
    ],
    [
      "path",
      {
        "d": "m6 8-4 4 4 4",
      },
    ],
    [
      "path",
      {
        "d": "m14.5 4-5 16",
      },
    ],
    ],
  },
  "Component": {
    // lucide/Component — inks 20.0x20.0 of 24
    shapes: [
    [
      "path",
      {
        "d": "M15.536 11.293a1 1 0 0 0 0 1.414l2.376 2.377a1 1 0 0 0 1.414 0l2.377-2.377a1 1 0 0 0 0-1.414l-2.377-2.377a1 1 0 0 0-1.414 0z",
      },
    ],
    [
      "path",
      {
        "d": "M2.297 11.293a1 1 0 0 0 0 1.414l2.377 2.377a1 1 0 0 0 1.414 0l2.377-2.377a1 1 0 0 0 0-1.414L6.088 8.916a1 1 0 0 0-1.414 0z",
      },
    ],
    [
      "path",
      {
        "d": "M8.916 17.912a1 1 0 0 0 0 1.415l2.377 2.376a1 1 0 0 0 1.414 0l2.377-2.376a1 1 0 0 0 0-1.415l-2.377-2.376a1 1 0 0 0-1.414 0z",
      },
    ],
    [
      "path",
      {
        "d": "M8.916 4.674a1 1 0 0 0 0 1.414l2.377 2.376a1 1 0 0 0 1.414 0l2.377-2.376a1 1 0 0 0 0-1.414l-2.377-2.377a1 1 0 0 0-1.414 0z",
      },
    ],
    ],
  },
  "Constrain": {
    // lucide/Scaling — inks 18.0x18.0 of 24
    shapes: [
    [
      "path",
      {
        "d": "M12 3H5a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2v-7",
      },
    ],
    [
      "path",
      {
        "d": "M14 15H9v-5",
      },
    ],
    [
      "path",
      {
        "d": "M16 3h5v5",
      },
    ],
    [
      "path",
      {
        "d": "M21 3 9 15",
      },
    ],
    ],
  },
  "Copy": {
    // foundations/copy — inks 18.0x22.0 of 24
    shapes: [
    [
      "path",
      {
        "d": "m20.12 4.707-2.826-2.828A3.026 3.026 0 0 0 15.17 1h-5.167A3.007 3.007 0 0 0 7 4.004V5h-.996A3.007 3.007 0 0 0 3 8.004v11.992A3.007 3.007 0 0 0 6.004 23h7.992A3.007 3.007 0 0 0 17 19.996V19h.996A3.007 3.007 0 0 0 21 15.996V6.83a2.98 2.98 0 0 0-.88-2.123zM18.586 6 16 6.001V3.414L18.586 6zM15 19.996C15 20.55 14.55 21 13.996 21H6.004C5.45 21 5 20.55 5 19.996V8.004C5 7.45 5.45 7 6.004 7H7v8.996A3.007 3.007 0 0 0 10.004 19H15v.996zM17.996 17h-7.992C9.45 17 9 16.55 9 15.996V4.004C9 3.45 9.45 3 10.004 3H14v3.001A2 2 0 0 0 15.999 8H19v7.996C19 16.55 18.55 17 17.996 17z",
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    ],
  },
  "CornerRadius": {
    // native — inks 18.0x18.0 of 24
    shapes: [
    [
      "path",
      {
        "d": "M4.5 21v-6a10.5 10.5 0 0 1 10.5 -10.5h6v1.5h-6a9 9 0 0 0 -9 9v6z",
        "fill-rule": "evenodd",
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    [
      "rect",
      {
        "x": 3,
        "y": 3,
        "width": 3,
        "height": 3,
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    [
      "rect",
      {
        "x": 18,
        "y": 18,
        "width": 3,
        "height": 3,
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    ],
  },
  "Cursor": {
    // native — inks 17.9x17.9 of 24
    shapes: [
    [
      "path",
      {
        "d": "M2.9458701710094917 4.500172213613091A1.2000000000000002 1.2000000000000002 0 0 1 4.500172213613091 2.9458701710094917L20.224904688491698 9.08655037105333A0.8999999999999999 0.8999999999999999 0 0 1 20.192392687617 10.775218664777976L14.231081834853054 12.842447428236444A2.25 2.25 0 0 0 12.842447428236444 14.231081834853054L10.775218664777976 20.192392687617A0.8999999999999999 0.8999999999999999 0 0 1 9.08655037105333 20.224904688491698L2.9458701710094917 4.500172213613091zM6.473293579598364 7.347588478562889A0.675 0.675 0 0 1 7.347588478562889 6.473293579598364L14.856257773356079 9.405511150922711A0.44999999999999996 0.44999999999999996 0 0 1 14.84000177291873 10.249845297785035L13.150211599969762 10.835820922275406A3.75 3.75 0 0 0 10.835820922275406 13.150211599969762L10.249845297785035 14.84000177291873A0.44999999999999996 0.44999999999999996 0 0 1 9.405511150922711 14.856257773356079L6.473293579598364 7.347588478562889z",
        "fill-rule": "evenodd",
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    ],
    // filled counterpart — inks 17.9x17.9 of 24
    filled: [
    [
      "path",
      {
        "d": "M2.9458701710094917 4.500172213613091A1.2000000000000002 1.2000000000000002 0 0 1 4.500172213613091 2.9458701710094917L20.224904688491698 9.08655037105333A0.8999999999999999 0.8999999999999999 0 0 1 20.192392687617 10.775218664777976L14.231081834853054 12.842447428236444A2.25 2.25 0 0 0 12.842447428236444 14.231081834853054L10.775218664777976 20.192392687617A0.8999999999999999 0.8999999999999999 0 0 1 9.08655037105333 20.224904688491698L2.9458701710094917 4.500172213613091z",
        "fill-rule": "evenodd",
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    ],
  },
  "ExternalLink": {
    // foundations/external-link — inks 22.0x22.0 of 24
    shapes: [
    [
      "path",
      {
        "d": "M22 14a1 1 0 0 0-1 1v4a2.002 2.002 0 0 1-2 2H5a2.002 2.002 0 0 1-2-2V5a2.002 2.002 0 0 1 2-2h4a1 1 0 0 0 0-2H5a4.004 4.004 0 0 0-4 4v14a4.004 4.004 0 0 0 4 4h14a4.004 4.004 0 0 0 4-4v-4a1 1 0 0 0-1-1zm0-13h-7a1 1 0 0 0 0 2h4.586L7.293 15.293a1 1 0 1 0 1.414 1.414L21 4.414V9a1 1 0 0 0 2 0V2a1 1 0 0 0-1-1z",
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    ],
  },
  "Eye": {
    // lucide/Eye — inks 20.0x14.0 of 24
    shapes: [
    [
      "path",
      {
        "d": "M2.062 12.348a1 1 0 0 1 0-.696 10.75 10.75 0 0 1 19.876 0 1 1 0 0 1 0 .696 10.75 10.75 0 0 1-19.876 0",
      },
    ],
    [
      "circle",
      {
        "cx": "12",
        "cy": "12",
        "r": "3",
      },
    ],
    ],
  },
  "EyeOff": {
    // lucide/EyeOff — inks 20.0x20.0 of 24
    shapes: [
    [
      "path",
      {
        "d": "M10.733 5.076a10.744 10.744 0 0 1 11.205 6.575 1 1 0 0 1 0 .696 10.747 10.747 0 0 1-1.444 2.49",
      },
    ],
    [
      "path",
      {
        "d": "M14.084 14.158a3 3 0 0 1-4.242-4.242",
      },
    ],
    [
      "path",
      {
        "d": "M17.479 17.499a10.75 10.75 0 0 1-15.417-5.151 1 1 0 0 1 0-.696 10.75 10.75 0 0 1 4.446-5.143",
      },
    ],
    [
      "path",
      {
        "d": "m2 2 20 20",
      },
    ],
    ],
  },
  "EyeOpen": {
    // lucide/Eye — inks 20.0x14.0 of 24
    shapes: [
    [
      "path",
      {
        "d": "M2.062 12.348a1 1 0 0 1 0-.696 10.75 10.75 0 0 1 19.876 0 1 1 0 0 1 0 .696 10.75 10.75 0 0 1-19.876 0",
      },
    ],
    [
      "circle",
      {
        "cx": "12",
        "cy": "12",
        "r": "3",
      },
    ],
    ],
  },
  "FlowHorizontal": {
    // native — inks 18.0x18.0 of 24
    shapes: [
    [
      "path",
      {
        "d": "M5.25 3h3a2.25 2.25 0 0 1 2.25 2.25v3a2.25 2.25 0 0 1 -2.25 2.25h-3a2.25 2.25 0 0 1 -2.25 -2.25v-3a2.25 2.25 0 0 1 2.25 -2.25zM5.25 4.5h3a0.75 0.75 0 0 1 0.75 0.75v3a0.75 0.75 0 0 1 -0.75 0.75h-3a0.75 0.75 0 0 1 -0.75 -0.75v-3a0.75 0.75 0 0 1 0.75 -0.75z",
        "fill-rule": "evenodd",
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    [
      "path",
      {
        "d": "M15.75 3h3a2.25 2.25 0 0 1 2.25 2.25v3a2.25 2.25 0 0 1 -2.25 2.25h-3a2.25 2.25 0 0 1 -2.25 -2.25v-3a2.25 2.25 0 0 1 2.25 -2.25zM15.75 4.5h3a0.75 0.75 0 0 1 0.75 0.75v3a0.75 0.75 0 0 1 -0.75 0.75h-3a0.75 0.75 0 0 1 -0.75 -0.75v-3a0.75 0.75 0 0 1 0.75 -0.75z",
        "fill-rule": "evenodd",
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    [
      "rect",
      {
        "x": 3,
        "y": 16.5,
        "width": 16.5,
        "height": 1.5,
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    [
      "path",
      {
        "d": "M17.25 13.5L21 17.25L17.25 21L15.149999999999999 21L18.9 17.25L15.149999999999999 13.5z",
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    ],
  },
  "FlowNone": {
    // native — inks 18.0x18.0 of 24
    shapes: [
    [
      "path",
      {
        "d": "M5.25 3h3a2.25 2.25 0 0 1 2.25 2.25v3a2.25 2.25 0 0 1 -2.25 2.25h-3a2.25 2.25 0 0 1 -2.25 -2.25v-3a2.25 2.25 0 0 1 2.25 -2.25zM5.25 4.5h3a0.75 0.75 0 0 1 0.75 0.75v3a0.75 0.75 0 0 1 -0.75 0.75h-3a0.75 0.75 0 0 1 -0.75 -0.75v-3a0.75 0.75 0 0 1 0.75 -0.75z",
        "fill-rule": "evenodd",
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    [
      "path",
      {
        "d": "M15.75 9h3a2.25 2.25 0 0 1 2.25 2.25v3a2.25 2.25 0 0 1 -2.25 2.25h-3a2.25 2.25 0 0 1 -2.25 -2.25v-3a2.25 2.25 0 0 1 2.25 -2.25zM15.75 10.5h3a0.75 0.75 0 0 1 0.75 0.75v3a0.75 0.75 0 0 1 -0.75 0.75h-3a0.75 0.75 0 0 1 -0.75 -0.75v-3a0.75 0.75 0 0 1 0.75 -0.75z",
        "fill-rule": "evenodd",
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    [
      "path",
      {
        "d": "M5.25 13.5h3a2.25 2.25 0 0 1 2.25 2.25v3a2.25 2.25 0 0 1 -2.25 2.25h-3a2.25 2.25 0 0 1 -2.25 -2.25v-3a2.25 2.25 0 0 1 2.25 -2.25zM5.25 15h3a0.75 0.75 0 0 1 0.75 0.75v3a0.75 0.75 0 0 1 -0.75 0.75h-3a0.75 0.75 0 0 1 -0.75 -0.75v-3a0.75 0.75 0 0 1 0.75 -0.75z",
        "fill-rule": "evenodd",
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    ],
  },
  "FlowVertical": {
    // native — inks 18.0x18.0 of 24
    shapes: [
    [
      "path",
      {
        "d": "M5.25 3h3a2.25 2.25 0 0 1 2.25 2.25v3a2.25 2.25 0 0 1 -2.25 2.25h-3a2.25 2.25 0 0 1 -2.25 -2.25v-3a2.25 2.25 0 0 1 2.25 -2.25zM5.25 4.5h3a0.75 0.75 0 0 1 0.75 0.75v3a0.75 0.75 0 0 1 -0.75 0.75h-3a0.75 0.75 0 0 1 -0.75 -0.75v-3a0.75 0.75 0 0 1 0.75 -0.75z",
        "fill-rule": "evenodd",
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    [
      "path",
      {
        "d": "M5.25 13.5h3a2.25 2.25 0 0 1 2.25 2.25v3a2.25 2.25 0 0 1 -2.25 2.25h-3a2.25 2.25 0 0 1 -2.25 -2.25v-3a2.25 2.25 0 0 1 2.25 -2.25zM5.25 15h3a0.75 0.75 0 0 1 0.75 0.75v3a0.75 0.75 0 0 1 -0.75 0.75h-3a0.75 0.75 0 0 1 -0.75 -0.75v-3a0.75 0.75 0 0 1 0.75 -0.75z",
        "fill-rule": "evenodd",
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    [
      "rect",
      {
        "x": 16.5,
        "y": 3,
        "width": 1.5,
        "height": 16.5,
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    [
      "path",
      {
        "d": "M13.5 17.25L17.25 21L21 17.25L21 15.149999999999999L17.25 18.9L13.5 15.149999999999999z",
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    ],
  },
  "FlowWrap": {
    // native — inks 18.0x18.0 of 24
    shapes: [
    [
      "path",
      {
        "d": "M5.25 3h3a2.25 2.25 0 0 1 2.25 2.25v3a2.25 2.25 0 0 1 -2.25 2.25h-3a2.25 2.25 0 0 1 -2.25 -2.25v-3a2.25 2.25 0 0 1 2.25 -2.25zM5.25 4.5h3a0.75 0.75 0 0 1 0.75 0.75v3a0.75 0.75 0 0 1 -0.75 0.75h-3a0.75 0.75 0 0 1 -0.75 -0.75v-3a0.75 0.75 0 0 1 0.75 -0.75z",
        "fill-rule": "evenodd",
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    [
      "path",
      {
        "d": "M15.75 3h3a2.25 2.25 0 0 1 2.25 2.25v3a2.25 2.25 0 0 1 -2.25 2.25h-3a2.25 2.25 0 0 1 -2.25 -2.25v-3a2.25 2.25 0 0 1 2.25 -2.25zM15.75 4.5h3a0.75 0.75 0 0 1 0.75 0.75v3a0.75 0.75 0 0 1 -0.75 0.75h-3a0.75 0.75 0 0 1 -0.75 -0.75v-3a0.75 0.75 0 0 1 0.75 -0.75z",
        "fill-rule": "evenodd",
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    [
      "path",
      {
        "d": "M5.25 13.5h3a2.25 2.25 0 0 1 2.25 2.25v3a2.25 2.25 0 0 1 -2.25 2.25h-3a2.25 2.25 0 0 1 -2.25 -2.25v-3a2.25 2.25 0 0 1 2.25 -2.25zM5.25 15h3a0.75 0.75 0 0 1 0.75 0.75v3a0.75 0.75 0 0 1 -0.75 0.75h-3a0.75 0.75 0 0 1 -0.75 -0.75v-3a0.75 0.75 0 0 1 0.75 -0.75z",
        "fill-rule": "evenodd",
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    [
      "path",
      {
        "d": "M15.75 13.5h3a2.25 2.25 0 0 1 2.25 2.25v3a2.25 2.25 0 0 1 -2.25 2.25h-3a2.25 2.25 0 0 1 -2.25 -2.25v-3a2.25 2.25 0 0 1 2.25 -2.25zM15.75 15h3a0.75 0.75 0 0 1 0.75 0.75v3a0.75 0.75 0 0 1 -0.75 0.75h-3a0.75 0.75 0 0 1 -0.75 -0.75v-3a0.75 0.75 0 0 1 0.75 -0.75z",
        "fill-rule": "evenodd",
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    ],
  },
  "GapColumn": {
    // native — inks 18.0x15.0 of 24
    shapes: [
    [
      "rect",
      {
        "x": 3,
        "y": 4.5,
        "width": 3,
        "height": 15,
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    [
      "rect",
      {
        "x": 18,
        "y": 4.5,
        "width": 3,
        "height": 15,
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    [
      "rect",
      {
        "x": 9,
        "y": 10.5,
        "width": 1.5,
        "height": 3,
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    [
      "rect",
      {
        "x": 13.5,
        "y": 10.5,
        "width": 1.5,
        "height": 3,
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    ],
  },
  "GapRow": {
    // native — inks 15.0x18.0 of 24
    shapes: [
    [
      "rect",
      {
        "x": 4.5,
        "y": 3,
        "width": 15,
        "height": 3,
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    [
      "rect",
      {
        "x": 4.5,
        "y": 18,
        "width": 15,
        "height": 3,
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    [
      "rect",
      {
        "x": 10.5,
        "y": 9,
        "width": 3,
        "height": 1.5,
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    [
      "rect",
      {
        "x": 10.5,
        "y": 13.5,
        "width": 3,
        "height": 1.5,
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    ],
  },
  "Grid2x2": {
    // lucide/Grid2x2 — inks 18.0x18.0 of 24
    shapes: [
    [
      "path",
      {
        "d": "M12 3v18",
      },
    ],
    [
      "path",
      {
        "d": "M3 12h18",
      },
    ],
    [
      "rect",
      {
        "x": "3",
        "y": "3",
        "width": "18",
        "height": "18",
        "rx": "2",
      },
    ],
    ],
  },
  "Image": {
    // foundations/image — inks 22.0x22.0 of 24
    shapes: [
    [
      "circle",
      {
        "cx": "6.5014",
        "cy": "6.50024",
        "r": "1.49951",
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    [
      "path",
      {
        "d": "M18.445 1H5.56A4.565 4.565 0 0 0 1 5.56v12.884a4.565 4.565 0 0 0 4.56 4.559h12.885a4.565 4.565 0 0 0 4.56-4.559V5.56A4.565 4.565 0 0 0 18.445 1zm2.56 17.444a2.562 2.562 0 0 1-2.56 2.559H5.56c-1.236 0-2.27-.88-2.508-2.047l3.483-3.483 2.741 2.74a1.91 1.91 0 0 0 2.699 0l5.468-5.467 3.562 3.563v2.135zm0-4.964-2.213-2.213a1.894 1.894 0 0 0-1.349-.559h-.002c-.51 0-.988.2-1.346.559l-5.469 5.467-2.742-2.742a1.91 1.91 0 0 0-2.697.001L3 16.18V5.56A2.563 2.563 0 0 1 5.56 3h12.885a2.563 2.563 0 0 1 2.56 2.56v7.92z",
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    ],
  },
  "Info": {
    // foundations/info — inks 21.0x21.0 of 24
    shapes: [
    [
      "circle",
      {
        "cx": "12.00061",
        "cy": "12.00452",
        "r": "10.5",
      },
    ],
    [
      "circle",
      {
        "cx": "11.81865",
        "cy": "7.70907",
        "r": "1.25",
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    [
      "path",
      {
        "d": "M10.56865 16.77725 13.43228 16.77725",
      },
    ],
    [
      "path",
      {
        "d": "M10.569 11.05 12 11.05 12 16.777",
      },
    ],
    ],
  },
  "InfoMark": {
    // foundations/info — inks 3.7x13.0 of 24
    shapes: [
    [
      "circle",
      {
        "cx": 11.764244999999999,
        "cy": 6.421790999999999,
        "r": 1.25,
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    [
      "path",
      {
        "d": "M10.1392 18.2104L13.862 18.2104",
      },
    ],
    [
      "path",
      {
        "d": "M10.1397 10.765L12 10.765L12 18.2101",
      },
    ],
    ],
  },
  "ListChecks": {
    // foundations/list-checks — inks 22.0x22.0 of 24
    shapes: [
    [
      "path",
      {
        "d": "M6.5,16.00195c-.55273,0-1,.44727-1,1s.44727,1,1,1h8.00098c.55273,0,1-.44727,1-1s-.44727-1-1-1H6.5ZM18.49902,12.00195c0-.55273-.44727-1-1-1H6.5c-.55273,0-1,.44727-1,1s.44727,1,1,1h10.99902c.55273,0,1-.44727,1-1ZM22,6.64941c-.55273,0-1,.44727-1,1v11.35059c0,1.10254-.89746,2-2,2H5c-1.10254,0-2-.89746-2-2V5c0-1.10254.89746-2,2-2h6.67578c.55273,0,1-.44727,1-1s-.44727-1-1-1h-6.67578C2.79395,1,1,2.79395,1,5v14c0,2.20605,1.79395,4,4,4h14c2.20605,0,4-1.79395,4-4V7.64941c0-.55273-.44727-1-1-1ZM6.5,6.00195c-.55273,0-1,.44824-1,1,0,.55273.44824,1,1,1l5.61914-.00195c.55273,0,1-.44824,1-1,0-.55273-.44824-1-1-1l-5.61914.00195ZM16.68066,7.31934c.19531.19531.45117.29297.70703.29297s.51172-.09766.70703-.29297l4.6123-4.6123c.39062-.39062.39062-1.02344,0-1.41406s-1.02344-.39062-1.41406,0l-3.90527,3.90527-1.68066-1.67969c-.39062-.39062-1.02344-.39062-1.41406,0s-.39062,1.02344,0,1.41406l2.3877,2.38672Z",
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    ],
  },
  "Lock": {
    // foundations/lock — inks 14.7x20.0 of 24
    shapes: [
    [
      "path",
      {
        "d": "M6.71 9.555h10.581a2.044 2.044 0 0 1 2.044 2.044v8.357a2.044 2.044 0 0 1-2.043 2.043H6.71a2.044 2.044 0 0 1-2.044-2.044V11.6A2.044 2.044 0 0 1 6.71 9.555zM7.78 9.555V6.222a4.222 4.222 0 0 1 8.444 0v3.333",
      },
    ],
    ],
  },
  "LockOpen": {
    // foundations/lock — inks 14.7x20.0 of 24
    shapes: [
    [
      "path",
      {
        "d": "M6.71 9.555h10.581a2.044 2.044 0 0 1 2.044 2.044v8.357a2.044 2.044 0 0 1-2.043 2.043H6.71a2.044 2.044 0 0 1-2.044-2.044V11.6A2.044 2.044 0 0 1 6.71 9.555zM7.78 9.555V6.222a4.222 4.222 0 0 1 8.359-.844",
      },
    ],
    ],
  },
  "MessageSquare": {
    // foundations/message-square — inks 15.6x15.6 of 24
    shapes: [
    [
      "path",
      {
        "d": "M18.7517 15.9062A7.7945 7.7945 0 1 0 15.9515 18.7259L19.8 19.8z",
      },
    ],
    ],
  },
  "Minimize": {
    // lucide/Minimize — inks 18.0x18.0 of 24
    shapes: [
    [
      "path",
      {
        "d": "M8 3v3a2 2 0 0 1-2 2H3",
      },
    ],
    [
      "path",
      {
        "d": "M21 8h-3a2 2 0 0 1-2-2V3",
      },
    ],
    [
      "path",
      {
        "d": "M3 16h3a2 2 0 0 1 2 2v3",
      },
    ],
    [
      "path",
      {
        "d": "M16 21v-3a2 2 0 0 1 2-2h3",
      },
    ],
    ],
  },
  "Minus": {
    // lucide/Minus — inks 14.0x0.0 of 24
    shapes: [
    [
      "path",
      {
        "d": "M5 12h14",
      },
    ],
    ],
  },
  "Moon": {
    // native — inks 19.2x18.0 of 24
    shapes: [
    [
      "path",
      {
        "d": "M21.569723122116326 16.445230666635656A10.5 10.5 0 1 1 5.571558805248048 2.9950768545427424A12.299999999999999 12.299999999999999 0 0 0 21.569723122116326 16.445230666635656z",
        "fill-rule": "evenodd",
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    ],
  },
  "Opacity": {
    // native — inks 18.0x18.0 of 24
    shapes: [
    [
      "path",
      {
        "d": "M3 3h18v18h-18zM4.5 4.5h15v15h-15z",
        "fill-rule": "evenodd",
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    [
      "rect",
      {
        "x": 4.5,
        "y": 4.5,
        "width": 7.5,
        "height": 7.5,
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    [
      "rect",
      {
        "x": 12,
        "y": 12,
        "width": 7.5,
        "height": 7.5,
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    ],
  },
  "PadBottom": {
    // native — inks 18.0x18.0 of 24
    shapes: [
    [
      "path",
      {
        "d": "M3 3h18v18h-18zM4.5 4.5h15v15h-15z",
        "fill-rule": "evenodd",
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    [
      "rect",
      {
        "x": 3,
        "y": 18,
        "width": 18,
        "height": 3,
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    ],
  },
  "PadLeft": {
    // native — inks 18.0x18.0 of 24
    shapes: [
    [
      "path",
      {
        "d": "M3 3h18v18h-18zM4.5 4.5h15v15h-15z",
        "fill-rule": "evenodd",
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    [
      "rect",
      {
        "x": 3,
        "y": 3,
        "width": 3,
        "height": 18,
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    ],
  },
  "PadRight": {
    // native — inks 18.0x18.0 of 24
    shapes: [
    [
      "path",
      {
        "d": "M3 3h18v18h-18zM4.5 4.5h15v15h-15z",
        "fill-rule": "evenodd",
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    [
      "rect",
      {
        "x": 18,
        "y": 3,
        "width": 3,
        "height": 18,
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    ],
  },
  "PadTop": {
    // native — inks 18.0x18.0 of 24
    shapes: [
    [
      "path",
      {
        "d": "M3 3h18v18h-18zM4.5 4.5h15v15h-15z",
        "fill-rule": "evenodd",
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    [
      "rect",
      {
        "x": 3,
        "y": 3,
        "width": 18,
        "height": 3,
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    ],
  },
  "PanelLeft": {
    // native — inks 18.0x18.0 of 24
    shapes: [
    [
      "path",
      {
        "d": "M6.75 3h10.5a3.75 3.75 0 0 1 3.75 3.75v10.5a3.75 3.75 0 0 1 -3.75 3.75h-10.5a3.75 3.75 0 0 1 -3.75 -3.75v-10.5a3.75 3.75 0 0 1 3.75 -3.75zM6.75 5.25h10.5a1.5 1.5 0 0 1 1.5 1.5v10.5a1.5 1.5 0 0 1 -1.5 1.5h-10.5a1.5 1.5 0 0 1 -1.5 -1.5v-10.5a1.5 1.5 0 0 1 1.5 -1.5z",
        "fill-rule": "evenodd",
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    [
      "rect",
      {
        "x": 9,
        "y": 5.25,
        "width": 2.25,
        "height": 13.5,
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    ],
    // filled counterpart — inks 18.0x18.0 of 24
    filled: [
    [
      "path",
      {
        "d": "M6.75 3h10.5a3.75 3.75 0 0 1 3.75 3.75v10.5a3.75 3.75 0 0 1 -3.75 3.75h-10.5a3.75 3.75 0 0 1 -3.75 -3.75v-10.5a3.75 3.75 0 0 1 3.75 -3.75zM6.75 5.25h10.5a1.5 1.5 0 0 1 1.5 1.5v10.5a1.5 1.5 0 0 1 -1.5 1.5h-10.5a1.5 1.5 0 0 1 -1.5 -1.5v-10.5a1.5 1.5 0 0 1 1.5 -1.5z",
        "fill-rule": "evenodd",
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    [
      "path",
      {
        "d": "M6.75 5.25h4.5v13.5h-4.5a1.5 1.5 0 0 1 -1.5 -1.5v-10.5a1.5 1.5 0 0 1 1.5 -1.5z",
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    ],
  },
  "PanelRight": {
    // native — inks 18.0x18.0 of 24
    shapes: [
    [
      "path",
      {
        "d": "M6.75 3h10.5a3.75 3.75 0 0 1 3.75 3.75v10.5a3.75 3.75 0 0 1 -3.75 3.75h-10.5a3.75 3.75 0 0 1 -3.75 -3.75v-10.5a3.75 3.75 0 0 1 3.75 -3.75zM6.75 5.25h10.5a1.5 1.5 0 0 1 1.5 1.5v10.5a1.5 1.5 0 0 1 -1.5 1.5h-10.5a1.5 1.5 0 0 1 -1.5 -1.5v-10.5a1.5 1.5 0 0 1 1.5 -1.5z",
        "fill-rule": "evenodd",
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    [
      "rect",
      {
        "x": 12.75,
        "y": 5.25,
        "width": 2.25,
        "height": 13.5,
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    ],
    // filled counterpart — inks 18.0x18.0 of 24
    filled: [
    [
      "path",
      {
        "d": "M6.75 3h10.5a3.75 3.75 0 0 1 3.75 3.75v10.5a3.75 3.75 0 0 1 -3.75 3.75h-10.5a3.75 3.75 0 0 1 -3.75 -3.75v-10.5a3.75 3.75 0 0 1 3.75 -3.75zM6.75 5.25h10.5a1.5 1.5 0 0 1 1.5 1.5v10.5a1.5 1.5 0 0 1 -1.5 1.5h-10.5a1.5 1.5 0 0 1 -1.5 -1.5v-10.5a1.5 1.5 0 0 1 1.5 -1.5z",
        "fill-rule": "evenodd",
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    [
      "path",
      {
        "d": "M12.75 5.25h4.5a1.5 1.5 0 0 1 1.5 1.5v10.5a1.5 1.5 0 0 1 -1.5 1.5h-4.5z",
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    ],
  },
  "Pencil": {
    // foundations/pencil — inks 20.0x20.0 of 24
    shapes: [
    [
      "path",
      {
        "d": "M6.172 22H2v-4.172L17.291 2.536a1.831 1.831 0 0 1 2.59 0l1.583 1.583a1.831 1.831 0 0 1 0 2.59z",
      },
    ],
    [
      "path",
      {
        "d": "M15.01842 4.80933 19.19067 8.98158",
      },
    ],
    ],
  },
  "Play": {
    // foundations/play — inks 17.1x19.0 of 24
    shapes: [
    [
      "path",
      {
        "d": "M4.664 21.172a2.441 2.441 0 0 1-1.22-2.116V4.944a2.444 2.444 0 0 1 3.667-2.12l12.222 7.057a2.444 2.444 0 0 1 0 4.235L7.111 21.172a2.446 2.446 0 0 1-2.447 0z",
      },
    ],
    ],
  },
  "Plus": {
    // foundations/plus — inks 14.0x14.0 of 24
    shapes: [
    [
      "path",
      {
        "d": "M5 12h14",
      },
    ],
    [
      "path",
      {
        "d": "M12 5v14",
      },
    ],
    ],
  },
  "Search": {
    // foundations/search — inks 20.0x20.0 of 24
    shapes: [
    [
      "path",
      {
        "d": "M19 10.5A8.5 8.5 0 1 1 10.5 2a8.5 8.5 0 0 1 8.5 8.5z",
      },
    ],
    [
      "path",
      {
        "d": "M16.51092 16.5109 22 21.99998",
      },
    ],
    ],
  },
  "Send": {
    // foundations/paper-plane-filled — inks 22.3x20.3 of 24
    shapes: [
    [
      "path",
      {
        "d": "M6.355 12.444L2.422 8.677A3.608 3.608 0 0 1 4.923 2.463L20.003 2.488A3.608 3.608 0 0 1 23.098 7.939L15.334 20.997A3.608 3.608 0 0 1 8.734 20.035L7.27 14.224L16.473 9.004A1 1 0 0 0 15.486 7.265L6.355 12.444Z",
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    ],
  },
  "SpaceBetweenHorizontal": {
    // native — inks 18.0x18.0 of 24
    shapes: [
    [
      "rect",
      {
        "x": 3,
        "y": 3,
        "width": 3,
        "height": 18,
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    [
      "rect",
      {
        "x": 18,
        "y": 3,
        "width": 3,
        "height": 18,
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    [
      "rect",
      {
        "x": 9,
        "y": 10.5,
        "width": 6,
        "height": 3,
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    ],
  },
  "SpaceBetweenVertical": {
    // native — inks 18.0x18.0 of 24
    shapes: [
    [
      "rect",
      {
        "x": 3,
        "y": 3,
        "width": 18,
        "height": 3,
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    [
      "rect",
      {
        "x": 3,
        "y": 18,
        "width": 18,
        "height": 3,
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    [
      "rect",
      {
        "x": 10.5,
        "y": 9,
        "width": 3,
        "height": 6,
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    ],
  },
  "Sparkles": {
    // foundations/sparkles — inks 22.0x22.1 of 24
    shapes: [
    [
      "path",
      {
        "d": "M14.008 5.687c-.469-.042-1.853-.33-1.853-.33a1.913 1.913 0 0 1-1.547-1.548s-.289-1.384-.33-1.852a.957.957 0 1 0-1.913 0c-.042.468-.331 1.852-.331 1.852a1.913 1.913 0 0 1-1.547 1.547s-1.384.29-1.853.33a.957.957 0 0 0 0 1.914c.469.041 1.853.33 1.853.33a1.913 1.913 0 0 1 1.547 1.548s.289 1.384.33 1.852a.957.957 0 1 0 1.914 0c.041-.468.33-1.852.33-1.852a1.913 1.913 0 0 1 1.547-1.547s1.384-.29 1.853-.331a.957.957 0 1 0 0-1.913zM22.043 14.396c-.397-.03-1.576-.245-1.576-.245a1.754 1.754 0 0 1-1.462-1.463s-.215-1.178-.246-1.576a.957.957 0 0 0-1.913 0c-.03.397-.24 1.575-.24 1.575a1.754 1.754 0 0 1-1.47 1.47s-1.177.21-1.574.24a.957.957 0 0 0 0 1.912c.397.03 1.575.24 1.575.24a1.754 1.754 0 0 1 1.47 1.47s.21 1.177.24 1.574a.957.957 0 0 0 1.912 0c.031-.397.246-1.575.246-1.575a1.754 1.754 0 0 1 1.462-1.463s1.179-.215 1.576-.246a.957.957 0 0 0 0-1.913zM9.545 17.293c-.325-.02-1.291-.16-1.291-.16a1.594 1.594 0 0 1-1.387-1.387s-.14-.966-.16-1.291a.957.957 0 0 0-1.913 0c-.02.325-.159 1.291-.159 1.291a1.594 1.594 0 0 1-1.387 1.387s-.967.14-1.291.16a.957.957 0 1 0 0 1.913c.324.02 1.291.159 1.291.159a1.594 1.594 0 0 1 1.387 1.387s.14.967.16 1.291a.957.957 0 1 0 1.912 0c.02-.324.16-1.291.16-1.291a1.594 1.594 0 0 1 1.387-1.387s.966-.14 1.29-.16a.957.957 0 1 0 0-1.912z",
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    ],
  },
  "Square": {
    // lucide/Square — inks 18.0x18.0 of 24
    shapes: [
    [
      "rect",
      {
        "width": "18",
        "height": "18",
        "x": "3",
        "y": "3",
        "rx": "2",
      },
    ],
    ],
  },
  "Sun": {
    // native — inks 18.8x18.8 of 24
    shapes: [
    [
      "circle",
      {
        "cx": 11.625,
        "cy": 11.625,
        "r": 4.875,
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    [
      "rect",
      {
        "x": 10.5,
        "y": 2.25,
        "width": 2.25,
        "height": 3,
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    [
      "rect",
      {
        "x": 10.5,
        "y": 18,
        "width": 2.25,
        "height": 3,
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    [
      "rect",
      {
        "x": 2.25,
        "y": 10.5,
        "width": 3,
        "height": 2.25,
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    [
      "rect",
      {
        "x": 18,
        "y": 10.5,
        "width": 3,
        "height": 2.25,
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    [
      "path",
      {
        "d": "M4.995 3.4040097423302678L7.1175 5.526509742330268L7.1175 8.708490257669734L4.995 6.585990257669732z",
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    [
      "path",
      {
        "d": "M16.1325 14.54150974233027L18.255 16.66400974233027L18.255 19.845990257669733L16.1325 17.72349025766973z",
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    [
      "path",
      {
        "d": "M18.255 3.4040097423302678L16.1325 5.526509742330268L16.1325 8.708490257669734L18.255 6.585990257669732z",
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    [
      "path",
      {
        "d": "M7.1175 14.54150974233027L4.995 16.66400974233027L4.995 19.845990257669733L7.1175 17.72349025766973z",
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    ],
  },
  "TextAlignBottom": {
    // native — inks 18.0x18.0 of 24
    shapes: [
    [
      "rect",
      {
        "x": 3,
        "y": 19.5,
        "width": 18,
        "height": 1.5,
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    [
      "rect",
      {
        "x": 10.5,
        "y": 3,
        "width": 1.5,
        "height": 15,
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    [
      "path",
      {
        "d": "M6.75 13.5L11.25 18L15.75 13.5L15.75 11.399999999999999L11.25 15.899999999999999L6.75 11.399999999999999z",
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    ],
  },
  "TextAlignCenter": {
    // native — inks 18.0x13.5 of 24
    shapes: [
    [
      "rect",
      {
        "x": 3,
        "y": 4.5,
        "width": 18,
        "height": 1.5,
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    [
      "rect",
      {
        "x": 6,
        "y": 10.5,
        "width": 12,
        "height": 1.5,
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    [
      "rect",
      {
        "x": 4.5,
        "y": 16.5,
        "width": 15,
        "height": 1.5,
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    ],
  },
  "TextAlignJustify": {
    // native — inks 18.0x13.5 of 24
    shapes: [
    [
      "rect",
      {
        "x": 3,
        "y": 4.5,
        "width": 18,
        "height": 1.5,
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    [
      "rect",
      {
        "x": 3,
        "y": 10.5,
        "width": 18,
        "height": 1.5,
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    [
      "rect",
      {
        "x": 3,
        "y": 16.5,
        "width": 18,
        "height": 1.5,
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    ],
  },
  "TextAlignLeft": {
    // native — inks 18.0x13.5 of 24
    shapes: [
    [
      "rect",
      {
        "x": 3,
        "y": 4.5,
        "width": 18,
        "height": 1.5,
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    [
      "rect",
      {
        "x": 3,
        "y": 10.5,
        "width": 12,
        "height": 1.5,
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    [
      "rect",
      {
        "x": 3,
        "y": 16.5,
        "width": 15,
        "height": 1.5,
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    ],
  },
  "TextAlignMiddle": {
    // native — inks 18.0x18.6 of 24
    shapes: [
    [
      "rect",
      {
        "x": 3,
        "y": 10.5,
        "width": 18,
        "height": 1.5,
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    [
      "rect",
      {
        "x": 10.5,
        "y": 3,
        "width": 1.5,
        "height": 6,
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    [
      "path",
      {
        "d": "M6.75 4.5L11.25 9L15.75 4.5L15.75 2.3999999999999995L11.25 6.8999999999999995L6.75 2.3999999999999995z",
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    [
      "rect",
      {
        "x": 10.5,
        "y": 15,
        "width": 1.5,
        "height": 6,
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    [
      "path",
      {
        "d": "M6.75 18L11.25 13.5L15.75 18L15.75 20.1L11.25 15.600000000000001L6.75 20.1z",
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    ],
  },
  "TextAlignRight": {
    // native — inks 18.0x13.5 of 24
    shapes: [
    [
      "rect",
      {
        "x": 3,
        "y": 4.5,
        "width": 18,
        "height": 1.5,
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    [
      "rect",
      {
        "x": 9,
        "y": 10.5,
        "width": 12,
        "height": 1.5,
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    [
      "rect",
      {
        "x": 6,
        "y": 16.5,
        "width": 15,
        "height": 1.5,
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    ],
  },
  "TextAlignTop": {
    // native — inks 18.0x18.0 of 24
    shapes: [
    [
      "rect",
      {
        "x": 3,
        "y": 3,
        "width": 18,
        "height": 1.5,
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    [
      "rect",
      {
        "x": 10.5,
        "y": 6,
        "width": 1.5,
        "height": 15,
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    [
      "path",
      {
        "d": "M6.75 10.5L11.25 6L15.75 10.5L15.75 12.600000000000001L11.25 8.100000000000001L6.75 12.600000000000001z",
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    ],
  },
  "ToolClose": {
    // native — inks 15.1x15.1 of 24
    shapes: [
    [
      "path",
      {
        "d": "M4.800000000000001 4.800000000000001A1.1249999999999998 1.1249999999999998 0 0 0 4.800000000000001 6.390990257669731L17.609009742330265 19.200000000000003A1.125 1.125 0 0 0 19.200000000000003 19.200000000000003L19.200000000000003 19.200000000000003A1.125 1.125 0 0 0 19.200000000000003 17.609009742330265L6.390990257669731 4.800000000000001A1.1249999999999998 1.1249999999999998 0 0 0 4.800000000000001 4.800000000000001L4.800000000000001 4.800000000000001z",
        "fill-rule": "evenodd",
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    [
      "path",
      {
        "d": "M4.800000000000001 19.200000000000003A1.1249999999999996 1.1249999999999996 0 0 0 6.390990257669731 19.200000000000003L19.200000000000003 6.390990257669731A1.1249999999999996 1.1249999999999996 0 0 0 19.200000000000003 4.800000000000001L19.200000000000003 4.799999999999999A1.125 1.125 0 0 0 17.60900974233027 4.800000000000001L4.800000000000001 17.60900974233027A1.125 1.125 0 0 0 4.799999999999999 19.200000000000003L4.800000000000001 19.200000000000003z",
        "fill-rule": "evenodd",
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    ],
  },
  "ToolRedo": {
    // native — inks 17.3x18.0 of 24
    shapes: [
    [
      "path",
      {
        "d": "M16.125 3L20.25 7.125L16.125 11.25L12.943019484660537 11.25L17.06801948466054 7.125L12.943019484660537 3z",
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    [
      "rect",
      {
        "x": 10.5,
        "y": 6,
        "width": 9,
        "height": 2.25,
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    [
      "path",
      {
        "d": "M10.5 21A7.5 7.5 0 0 1 10.5 6L10.5 8.25A5.25 5.25 0 0 0 10.5 18.75z",
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    [
      "rect",
      {
        "x": 10.5,
        "y": 18.75,
        "width": 4.5,
        "height": 2.25,
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    ],
  },
  "ToolUndo": {
    // native — inks 17.3x18.0 of 24
    shapes: [
    [
      "path",
      {
        "d": "M7.875 3L3.75 7.125L7.875 11.25L11.056980515339465 11.25L6.931980515339465 7.125L11.056980515339465 3z",
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    [
      "rect",
      {
        "x": 4.5,
        "y": 6,
        "width": 9,
        "height": 2.25,
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    [
      "path",
      {
        "d": "M13.5 6A7.5 7.5 0 0 1 13.5 21L13.5 18.75A5.25 5.25 0 0 0 13.5 8.25z",
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    [
      "rect",
      {
        "x": 9,
        "y": 18.75,
        "width": 4.5,
        "height": 2.25,
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    ],
  },
  "Trash": {
    // foundations/trash-2 — inks 18.2x20.0 of 24
    shapes: [
    [
      "path",
      {
        "d": "M2.87595 4.72727 21.12405 4.72727",
      },
    ],
    [
      "path",
      {
        "d": "M8.818 4.727v-1.59A1.136 1.136 0 0 1 9.954 2h4.092a1.136 1.136 0 0 1 1.136 1.136v1.591",
      },
    ],
    [
      "path",
      {
        "d": "m4.377 4.727 1.987 15.88A1.59 1.59 0 0 0 7.942 22h8.116a1.59 1.59 0 0 0 1.578-1.393l1.987-15.88",
      },
    ],
    ],
  },
  "Type": {
    // lucide/Type — inks 16.0x16.0 of 24
    shapes: [
    [
      "path",
      {
        "d": "M12 4v16",
      },
    ],
    [
      "path",
      {
        "d": "M4 7V5a1 1 0 0 1 1-1h14a1 1 0 0 1 1 1v2",
      },
    ],
    [
      "path",
      {
        "d": "M9 20h6",
      },
    ],
    ],
  },
  "WrapText": {
    // lucide/WrapText — inks 18.0x17.0 of 24
    shapes: [
    [
      "path",
      {
        "d": "m16 16-3 3 3 3",
      },
    ],
    [
      "path",
      {
        "d": "M3 12h14.5a1 1 0 0 1 0 7H13",
      },
    ],
    [
      "path",
      {
        "d": "M3 19h6",
      },
    ],
    [
      "path",
      {
        "d": "M3 5h18",
      },
    ],
    ],
  },
  "X": {
    // foundations/x — inks 18.0x18.0 of 24
    shapes: [
    [
      "path",
      {
        "d": "m13.414 12 7.293-7.293a1 1 0 1 0-1.414-1.414L12 10.586 4.707 3.293a1 1 0 1 0-1.414 1.414L10.586 12l-7.293 7.293a1 1 0 1 0 1.414 1.414L12 13.414l7.293 7.293a.997.997 0 0 0 1.414 0 1 1 0 0 0 0-1.414L13.414 12z",
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    ],
  },
} as const satisfies Record<string, IconData>

export type IconName = keyof typeof ICONS

export const ICON_NAMES = Object.keys(ICONS) as IconName[]

/**
 * The glyphs authored on the native 16 lattice rather than taken from Lucide.
 *
 * Exported so the rung rule can be CHECKED rather than just written down: these
 * land on whole device pixels only at a size that is a multiple of 8, so they
 * may be drawn at `icon.action` (16) or `icon.feature` (24), never at marker
 * 12, inline 14, chrome 18 or header 20. `test/icon-cases.mjs` reads this list
 * and greps the source for a call that breaks it.
 *
 * A comment could not carry this. The mistake it prevents — reaching for
 * `tokens.icon.marker` because the text beside the glyph is 12px — is locally
 * reasonable every single time, and the result looks fine until it is set
 * beside a glyph drawn at 16.
 */
export const NATIVE_ICON_NAMES = ["AlignCenterHorizontal","AlignCenterVertical","AlignEndHorizontal","AlignEndVertical","AlignStartHorizontal","AlignStartVertical","ArrangeBack","ArrangeBackward","ArrangeForward","ArrangeFront","CornerRadius","Cursor","FlowHorizontal","FlowNone","FlowVertical","FlowWrap","GapColumn","GapRow","Moon","Opacity","PadBottom","PadLeft","PadRight","PadTop","PanelLeft","PanelRight","SpaceBetweenHorizontal","SpaceBetweenVertical","Sun","TextAlignBottom","TextAlignCenter","TextAlignJustify","TextAlignLeft","TextAlignMiddle","TextAlignRight","TextAlignTop","ToolClose","ToolRedo","ToolUndo"] as const satisfies readonly IconName[]

/** The rungs a native glyph renders crisply at — every multiple of 8 on the ramp. */
export const NATIVE_ICON_SIZES = [16, 24] as const satisfies readonly IconSize[]

const SVG_NS = "http://www.w3.org/2000/svg"

function build(node: IconNode): SVGElement {
  const [tag, attrs, children] = node
  const element = document.createElementNS(SVG_NS, tag)
  for (const [key, value] of Object.entries(attrs)) element.setAttribute(key, String(value))
  for (const child of children ?? []) element.append(build(child))
  return element
}

/**
 * Draw one glyph from its data.
 *
 * Exported so the host's own icon set — served by the loopback `/icons` route
 * and offered as variants in the inspector — is drawn by the same rules as
 * these. Two renderers would be two answers to "how big is a glyph", and only
 * one of them would be right.
 */
export function drawIcon(data: IconData, size: IconSize = 16, weight: IconWeight = "auto"): SVGSVGElement {
  const svg = document.createElementNS(SVG_NS, "svg")
  svg.setAttribute("width", String(size))
  svg.setAttribute("height", String(size))
  svg.setAttribute("viewBox", "0 0 24 24")
  // The fill is opt-in and the outline is what `auto` means: a flood reads only
  // on a closed silhouette, so a caller asks for it knowing which mark it holds.
  svg.setAttribute("fill", weight === "filled" ? "currentColor" : "none")
  svg.setAttribute("stroke", "currentColor")
  const stroke = STROKE_FOR_SIZE[size]
  svg.setAttribute("stroke-width", String(stroke))
  svg.style.setProperty(ICON_STROKE_VARIABLE, String(stroke))
  svg.setAttribute("stroke-linecap", "round")
  svg.setAttribute("stroke-linejoin", "round")
  svg.setAttribute(ICON_MARKER_ATTRIBUTE, "")
  svg.setAttribute("aria-hidden", "true")
  // The counterpart when the glyph has one, its own shapes otherwise. A mark
  // whose runs are all open floods to nothing, and a toggle drawing it would
  // report the same picture in both states.
  const shapes = weight === "filled" && data.filled ? data.filled : data.shapes
  for (const node of shapes) svg.append(build(node))
  return svg
}

/**
 * One glyph, sized and decorative.
 *
 * Colour comes from `currentColor`, never a token: the same mark is drawn on a
 * rest row, a hovered row and a filled selected row, and only the caller knows
 * which.
 */
export function icon(name: IconName, size: IconSize = 16, weight: IconWeight = "auto"): SVGSVGElement {
  const svg = drawIcon(ICONS[name], size, weight)
  /*
   * THE MARKER CARRIES THE NAME NOW, where it used to carry an empty string.
   *
   * Every rule that reads it is written `svg[data-de-glyph]`, which matches on
   * presence and is unaffected. What the value adds is the ability to say
   * something about ONE mark — and there is exactly one thing worth saying,
   * which is the optical correction for `Cursor` in `css/icons.ts`.
   *
   * Set here and not in `drawIcon`, because `drawIcon` also renders the HOST
   * app's own icons, whose names belong to a set this package did not author. A
   * rule written against one of ours must not be able to reach one of theirs.
   */
  svg.setAttribute(ICON_MARKER_ATTRIBUTE, name)
  return svg
}

/**
 * A glyph from the HOST's own icon set, which is a different set of rules.
 *
 * The app being edited ships its own icons, served by the loopback `/icons`
 * route so the inspector can offer one in place of another. Those are drawn the
 * way their author drew them: one weight, whatever grid and stroke they use,
 * nothing normalised. They must not be squeezed into the chrome's shape — this
 * editor does not get to decide that someone else's icon is a stroke family, or
 * to re-window a glyph it is about to write into their source. A second, smaller
 * renderer is the honest way to say that.
 */
export interface HostIconData {
  nodes: IconNode[]
  rootFill: string
  rootStroke?: string
}

export function drawHostIcon(data: HostIconData, size: IconSize = 16): SVGSVGElement {
  const svg = document.createElementNS(SVG_NS, "svg")
  svg.setAttribute("width", String(size))
  svg.setAttribute("height", String(size))
  svg.setAttribute("viewBox", "0 0 24 24")
  svg.setAttribute("fill", data.rootFill === "none" ? "none" : "currentColor")
  if (data.rootStroke) {
    svg.setAttribute("stroke", "currentColor")
    svg.setAttribute("stroke-width", "2")
    svg.setAttribute("stroke-linecap", "round")
    svg.setAttribute("stroke-linejoin", "round")
  }
  svg.setAttribute("aria-hidden", "true")
  for (const node of data.nodes) svg.append(build(node))
  return svg
}
