/**
 * The editor chrome's glyph set.
 *
 * GENERATED by `tools/build-icons.mjs` from Lucide 1.46.0
 * (https://lucide.dev/icons, ISC) — do not hand-edit. To swap a glyph, change
 * the mapping in that script and re-run it.
 *
 * Lucide is a STROKE family on a single 24x24 grid, and three things follow from
 * that, each of which used to be the opposite here:
 *
 *   - ONE drawing per glyph, with a fill painted over it rather than a second
 *     drawing. Lucide ships no filled counterparts, and flooding an outline
 *     with `currentColor` reads only for a closed silhouette — but every mark a
 *     TOGGLE in this chrome draws is closed, so the pointer, the bubble and the
 *     layer stack all fill correctly from their own paths and cannot drift in
 *     size from the outline they replace. A row or a tab that reports itself
 *     `aria-selected` still gets the heavier stroke from the stylesheet (see
 *     `css/icons.ts`), because a list has its neighbours on screen to be
 *     compared against and a lone toolbar button does not.
 *
 *   - A `filled` array, on the few glyphs a flood cannot serve. A mark made
 *     only of open runs has no area to flood — `SlidersHorizontal` came out
 *     identical in both states — so those carry an authored counterpart, held
 *     by the generator to the same ink extent as their outline.
 *
 *   - NO per-glyph window. Nothing is re-fitted by widening its viewBox: that
 *     scales a stroke along with the drawing and lands it under weight, trading
 *     a size error for a weight error. The extents are deliberately uneven — a
 *     chevron inks 12 of the grid and a layer stack 20 — because that is
 *     Lucide's own optical sizing.
 *
 *   - Stroke width is compensated per SIZE, which is what actually makes the
 *     family cohere across the ramp. See `STROKE_FOR_SIZE`.
 */

export type IconNode = [
  tag: string,
  attrs: Record<string, string | number>,
  children?: IconNode[],
]

/**
 * One glyph: Lucide's shapes, on Lucide's grid.
 *
 * `filled` is the counterpart drawn for the marks a flood cannot express — see
 * the header. Absent, which is the usual case, the filled weight paints the
 * same shapes with `currentColor`, so the two states cannot be different marks.
 */
export interface IconData {
  shapes: IconNode[]
  filled?: IconNode[]
}

/**
 * Which weight a glyph is asked for.
 *
 * `auto` is the outline, and lets the stylesheet add the extra stroke when the
 * control reports itself selected in a list of its peers — which is how "on
 * means heavier" stays one rule rather than 80 call sites.
 *
 * `filled` is what a TOGGLE asks for while it is on. A stroke half a unit
 * heavier is a relative signal: legible beside the same glyph in its off state,
 * and unreadable on a button sitting on its own, which is exactly the case a
 * mode indicator has to answer. Solid or hollow needs nothing to compare
 * against.
 */
export type IconWeight = "outline" | "filled" | "auto"

/**
 * The only sizes a glyph may be drawn at: the ramp in `tokens.icon`.
 *
 * A union rather than `number`, so a size off the ramp fails to compile instead
 * of shipping. The set drifted to seven sizes once — 10, 12, 13, 14, 16, 18 and
 * 20, each added at one call site by someone reaching for the value that looked
 * right next to the text beside it. Nothing caught it, because every one of
 * those calls was locally reasonable.
 *
 * Call sites should pass `tokens.icon.row` and friends rather than the number,
 * which is what makes the ramp readable at the point of use; this type is the
 * backstop for the ones that do not.
 */
export type IconSize = 10 | 12 | 16 | 20 | 24 | 32

/**
 * The stroke each rung wears, in grid units.
 *
 * The half of "one family" a stroke set has to state outright and a fill set
 * gets for free. Rendered thickness is `width * size / 24`, so Lucide's native
 * 2 held flat across this ramp would draw one mark 0.83px thick at `mark` and
 * 2.67px at `hero` — a threefold spread in apparent weight between two drawings
 * the design system calls the same icon. The small end is the end that fails:
 * under about 1px a stroke antialiases into a grey suggestion of itself, which
 * is how an icon comes to look "too small" while measuring exactly the size it
 * was asked for.
 *
 * Compensated, rendered thickness lands on 1.15, 1.25, 1.50, 1.77, 2.00 and
 * 2.33px. Deliberately not flat — a 32px glyph drawn at a 12px glyph's thickness
 * reads as a hairline rather than as the same mark enlarged — but it travels a
 * fifth as far as the uncompensated one. 24 keeps Lucide's own 2, so the set
 * looks like Lucide at Lucide's size.
 *
 * `tools/build-icons.mjs` measures every glyph's clearance inside the grid and
 * fails the build if the heaviest rung here would clip one.
 */
const STROKE_FOR_SIZE: Record<IconSize, number> = {
  10: 2.75,
  12: 2.5,
  16: 2.25,
  20: 2.125,
  24: 2,
  32: 1.75,
}

/**
 * The stroke width, published as a custom property the stylesheet can build on.
 *
 * Written ALONGSIDE the `stroke-width` attribute rather than instead of it. The
 * attribute is the value that is always right, including with no stylesheet at
 * all; the property is what lets one CSS rule say "pressed is half a unit
 * heavier" without knowing which rung the glyph was drawn at.
 */
export const ICON_STROKE_VARIABLE = "--de-icon-stroke"

/**
 * What marks an `<svg>` as one of OURS.
 *
 * The state rule in `css/icons.ts` leans on the custom property above, and
 * without this it would also reach two kinds of `<svg>` it has no business
 * restyling: the host's own icons, which `drawHostIcon` renders inside the
 * inspector exactly as their author drew them, and any `<svg>` the app being
 * edited happens to place inside a selected row. Both would pick up the
 * property's fallback and get re-weighted on selection — the editor quietly
 * redrawing someone else's artwork.
 */
export const ICON_MARKER_ATTRIBUTE = "data-de-glyph"

const ICONS = {
  "AlignCenterHorizontal": {
    // native — inks 18.0x16.5 of 24
    shapes: [
    [
      "rect",
      {
        "x": 3,
        "y": 10.5,
        "width": 18,
        "height": 1.5,
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    [
      "rect",
      {
        "x": 7.5,
        "y": 3,
        "width": 3,
        "height": 16.5,
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    [
      "rect",
      {
        "x": 13.5,
        "y": 6,
        "width": 3,
        "height": 10.5,
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    ],
  },
  "AlignCenterVertical": {
    // native — inks 16.5x18.0 of 24
    shapes: [
    [
      "rect",
      {
        "x": 10.5,
        "y": 3,
        "width": 1.5,
        "height": 18,
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    [
      "rect",
      {
        "x": 3,
        "y": 7.5,
        "width": 16.5,
        "height": 3,
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    [
      "rect",
      {
        "x": 6,
        "y": 13.5,
        "width": 10.5,
        "height": 3,
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    ],
  },
  "AlignEndHorizontal": {
    // native — inks 18.0x18.0 of 24
    shapes: [
    [
      "rect",
      {
        "x": 3,
        "y": 19.5,
        "width": 18,
        "height": 1.5,
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    [
      "rect",
      {
        "x": 7.5,
        "y": 3,
        "width": 3,
        "height": 13.5,
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    [
      "rect",
      {
        "x": 13.5,
        "y": 9,
        "width": 3,
        "height": 7.5,
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    ],
  },
  "AlignEndVertical": {
    // native — inks 18.0x18.0 of 24
    shapes: [
    [
      "rect",
      {
        "x": 19.5,
        "y": 3,
        "width": 1.5,
        "height": 18,
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    [
      "rect",
      {
        "x": 3,
        "y": 7.5,
        "width": 13.5,
        "height": 3,
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    [
      "rect",
      {
        "x": 9,
        "y": 13.5,
        "width": 7.5,
        "height": 3,
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    ],
  },
  "AlignStartHorizontal": {
    // native — inks 18.0x18.0 of 24
    shapes: [
    [
      "rect",
      {
        "x": 3,
        "y": 3,
        "width": 18,
        "height": 1.5,
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    [
      "rect",
      {
        "x": 7.5,
        "y": 7.5,
        "width": 3,
        "height": 13.5,
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    [
      "rect",
      {
        "x": 13.5,
        "y": 7.5,
        "width": 3,
        "height": 7.5,
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    ],
  },
  "AlignStartVertical": {
    // native — inks 18.0x18.0 of 24
    shapes: [
    [
      "rect",
      {
        "x": 3,
        "y": 3,
        "width": 1.5,
        "height": 18,
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    [
      "rect",
      {
        "x": 7.5,
        "y": 7.5,
        "width": 13.5,
        "height": 3,
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    [
      "rect",
      {
        "x": 7.5,
        "y": 13.5,
        "width": 7.5,
        "height": 3,
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    ],
  },
  "ArrangeBack": {
    // native — inks 18.0x18.0 of 24
    shapes: [
    [
      "rect",
      {
        "x": 3,
        "y": 19.5,
        "width": 18,
        "height": 1.5,
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    [
      "rect",
      {
        "x": 10.5,
        "y": 3,
        "width": 1.5,
        "height": 14.25,
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    [
      "path",
      {
        "d": "M6.75 12.75L11.25 17.25L15.75 12.75L15.75 10.649999999999999L11.25 15.149999999999999L6.75 10.649999999999999z",
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    ],
  },
  "ArrangeBackward": {
    // native — inks 9.0x16.5 of 24
    shapes: [
    [
      "rect",
      {
        "x": 10.5,
        "y": 3,
        "width": 1.5,
        "height": 16.5,
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    [
      "path",
      {
        "d": "M6.75 15L11.25 19.5L15.75 15L15.75 12.899999999999999L11.25 17.4L6.75 12.899999999999999z",
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    ],
  },
  "ArrangeForward": {
    // native — inks 9.0x16.5 of 24
    shapes: [
    [
      "rect",
      {
        "x": 10.5,
        "y": 4.5,
        "width": 1.5,
        "height": 16.5,
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    [
      "path",
      {
        "d": "M6.75 9L11.25 4.5L15.75 9L15.75 11.100000000000001L11.25 6.6000000000000005L6.75 11.100000000000001z",
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    ],
  },
  "ArrangeFront": {
    // native — inks 18.0x18.0 of 24
    shapes: [
    [
      "rect",
      {
        "x": 3,
        "y": 3,
        "width": 18,
        "height": 1.5,
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    [
      "rect",
      {
        "x": 10.5,
        "y": 6.75,
        "width": 1.5,
        "height": 14.25,
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    [
      "path",
      {
        "d": "M6.75 11.25L11.25 6.75L15.75 11.25L15.75 13.350000000000001L11.25 8.850000000000001L6.75 13.350000000000001z",
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    ],
  },
  "ArrowDown": {
    // lucide/ArrowDown — inks 14.0x14.0 of 24
    shapes: [
    [
      "path",
      {
        "d": "M12 5v14",
      },
    ],
    [
      "path",
      {
        "d": "m19 12-7 7-7-7",
      },
    ],
    ],
  },
  "ArrowDownToLine": {
    // lucide/ArrowDownToLine — inks 14.0x18.0 of 24
    shapes: [
    [
      "path",
      {
        "d": "M12 17V3",
      },
    ],
    [
      "path",
      {
        "d": "m6 11 6 6 6-6",
      },
    ],
    [
      "path",
      {
        "d": "M19 21H5",
      },
    ],
    ],
  },
  "ArrowRight": {
    // lucide/ArrowRight — inks 14.0x14.0 of 24
    shapes: [
    [
      "path",
      {
        "d": "M5 12h14",
      },
    ],
    [
      "path",
      {
        "d": "m12 5 7 7-7 7",
      },
    ],
    ],
  },
  "ArrowUp": {
    // lucide/ArrowUp — inks 14.0x14.0 of 24
    shapes: [
    [
      "path",
      {
        "d": "m5 12 7-7 7 7",
      },
    ],
    [
      "path",
      {
        "d": "M12 19V5",
      },
    ],
    ],
  },
  "ArrowUpToLine": {
    // lucide/ArrowUpToLine — inks 14.0x18.0 of 24
    shapes: [
    [
      "path",
      {
        "d": "M5 3h14",
      },
    ],
    [
      "path",
      {
        "d": "m18 13-6-6-6 6",
      },
    ],
    [
      "path",
      {
        "d": "M12 7v14",
      },
    ],
    ],
  },
  "Ban": {
    // lucide/Ban — inks 20.0x20.0 of 24
    shapes: [
    [
      "circle",
      {
        "cx": "12",
        "cy": "12",
        "r": "10",
      },
    ],
    [
      "path",
      {
        "d": "M4.929 4.929 19.07 19.071",
      },
    ],
    ],
  },
  "Check": {
    // lucide/Check — inks 16.0x11.0 of 24
    shapes: [
    [
      "path",
      {
        "d": "M20 6 9 17l-5-5",
      },
    ],
    ],
  },
  "ChevronDown": {
    // lucide/ChevronDown — inks 12.0x6.0 of 24
    shapes: [
    [
      "path",
      {
        "d": "m6 9 6 6 6-6",
      },
    ],
    ],
  },
  "ChevronRight": {
    // lucide/ChevronRight — inks 6.0x12.0 of 24
    shapes: [
    [
      "path",
      {
        "d": "m9 18 6-6-6-6",
      },
    ],
    ],
  },
  "ChevronsDownUp": {
    // lucide/ChevronsDownUp — inks 10.0x16.0 of 24
    shapes: [
    [
      "path",
      {
        "d": "m7 20 5-5 5 5",
      },
    ],
    [
      "path",
      {
        "d": "m7 4 5 5 5-5",
      },
    ],
    ],
  },
  "ChevronsUpDown": {
    // lucide/ChevronsUpDown — inks 10.0x16.0 of 24
    shapes: [
    [
      "path",
      {
        "d": "m7 15 5 5 5-5",
      },
    ],
    [
      "path",
      {
        "d": "m7 9 5-5 5 5",
      },
    ],
    ],
  },
  "Circle": {
    // lucide/Circle — inks 20.0x20.0 of 24
    shapes: [
    [
      "circle",
      {
        "cx": "12",
        "cy": "12",
        "r": "10",
      },
    ],
    ],
  },
  "Code": {
    // lucide/Code — inks 20.0x12.0 of 24
    shapes: [
    [
      "path",
      {
        "d": "m16 18 6-6-6-6",
      },
    ],
    [
      "path",
      {
        "d": "m8 6-6 6 6 6",
      },
    ],
    ],
  },
  "Component": {
    // lucide/Component — inks 20.0x20.0 of 24
    shapes: [
    [
      "path",
      {
        "d": "M15.536 11.293a1 1 0 0 0 0 1.414l2.376 2.377a1 1 0 0 0 1.414 0l2.377-2.377a1 1 0 0 0 0-1.414l-2.377-2.377a1 1 0 0 0-1.414 0z",
      },
    ],
    [
      "path",
      {
        "d": "M2.297 11.293a1 1 0 0 0 0 1.414l2.377 2.377a1 1 0 0 0 1.414 0l2.377-2.377a1 1 0 0 0 0-1.414L6.088 8.916a1 1 0 0 0-1.414 0z",
      },
    ],
    [
      "path",
      {
        "d": "M8.916 17.912a1 1 0 0 0 0 1.415l2.377 2.376a1 1 0 0 0 1.414 0l2.377-2.376a1 1 0 0 0 0-1.415l-2.377-2.376a1 1 0 0 0-1.414 0z",
      },
    ],
    [
      "path",
      {
        "d": "M8.916 4.674a1 1 0 0 0 0 1.414l2.377 2.376a1 1 0 0 0 1.414 0l2.377-2.376a1 1 0 0 0 0-1.414l-2.377-2.377a1 1 0 0 0-1.414 0z",
      },
    ],
    ],
  },
  "Constrain": {
    // lucide/Scaling — inks 18.0x18.0 of 24
    shapes: [
    [
      "path",
      {
        "d": "M12 3H5a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2v-7",
      },
    ],
    [
      "path",
      {
        "d": "M14 15H9v-5",
      },
    ],
    [
      "path",
      {
        "d": "M16 3h5v5",
      },
    ],
    [
      "path",
      {
        "d": "M21 3 9 15",
      },
    ],
    ],
  },
  "Copy": {
    // lucide/Copy — inks 20.0x20.0 of 24
    shapes: [
    [
      "rect",
      {
        "width": "14",
        "height": "14",
        "x": "8",
        "y": "8",
        "rx": "2",
        "ry": "2",
      },
    ],
    [
      "path",
      {
        "d": "M4 16c-1.1 0-2-.9-2-2V4c0-1.1.9-2 2-2h10c1.1 0 2 .9 2 2",
      },
    ],
    ],
  },
  "CornerRadius": {
    // native — inks 18.0x18.0 of 24
    shapes: [
    [
      "path",
      {
        "d": "M4.5 21v-6a10.5 10.5 0 0 1 10.5 -10.5h6v1.5h-6a9 9 0 0 0 -9 9v6z",
        "fill-rule": "evenodd",
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    [
      "rect",
      {
        "x": 3,
        "y": 3,
        "width": 3,
        "height": 3,
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    [
      "rect",
      {
        "x": 18,
        "y": 18,
        "width": 3,
        "height": 3,
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    ],
  },
  "Cursor": {
    // native — inks 17.9x17.9 of 24
    shapes: [
    [
      "path",
      {
        "d": "M2.9458701710094917 4.500172213613091A1.2000000000000002 1.2000000000000002 0 0 1 4.500172213613091 2.9458701710094917L20.224904688491698 9.08655037105333A0.8999999999999999 0.8999999999999999 0 0 1 20.192392687617 10.775218664777976L14.231081834853054 12.842447428236444A2.25 2.25 0 0 0 12.842447428236444 14.231081834853054L10.775218664777976 20.192392687617A0.8999999999999999 0.8999999999999999 0 0 1 9.08655037105333 20.224904688491698L2.9458701710094917 4.500172213613091zM6.473293579598364 7.347588478562889A0.675 0.675 0 0 1 7.347588478562889 6.473293579598364L14.856257773356079 9.405511150922711A0.44999999999999996 0.44999999999999996 0 0 1 14.84000177291873 10.249845297785035L13.150211599969762 10.835820922275406A3.75 3.75 0 0 0 10.835820922275406 13.150211599969762L10.249845297785035 14.84000177291873A0.44999999999999996 0.44999999999999996 0 0 1 9.405511150922711 14.856257773356079L6.473293579598364 7.347588478562889z",
        "fill-rule": "evenodd",
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    ],
    // filled counterpart — inks 17.9x17.9 of 24
    filled: [
    [
      "path",
      {
        "d": "M2.9458701710094917 4.500172213613091A1.2000000000000002 1.2000000000000002 0 0 1 4.500172213613091 2.9458701710094917L20.224904688491698 9.08655037105333A0.8999999999999999 0.8999999999999999 0 0 1 20.192392687617 10.775218664777976L14.231081834853054 12.842447428236444A2.25 2.25 0 0 0 12.842447428236444 14.231081834853054L10.775218664777976 20.192392687617A0.8999999999999999 0.8999999999999999 0 0 1 9.08655037105333 20.224904688491698L2.9458701710094917 4.500172213613091z",
        "fill-rule": "evenodd",
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    ],
  },
  "ExternalLink": {
    // lucide/ExternalLink — inks 18.0x18.0 of 24
    shapes: [
    [
      "path",
      {
        "d": "M15 3h6v6",
      },
    ],
    [
      "path",
      {
        "d": "M10 14 21 3",
      },
    ],
    [
      "path",
      {
        "d": "M18 13v6a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h6",
      },
    ],
    ],
  },
  "Eye": {
    // lucide/Eye — inks 20.0x14.0 of 24
    shapes: [
    [
      "path",
      {
        "d": "M2.062 12.348a1 1 0 0 1 0-.696 10.75 10.75 0 0 1 19.876 0 1 1 0 0 1 0 .696 10.75 10.75 0 0 1-19.876 0",
      },
    ],
    [
      "circle",
      {
        "cx": "12",
        "cy": "12",
        "r": "3",
      },
    ],
    ],
  },
  "EyeOff": {
    // lucide/EyeOff — inks 20.0x20.0 of 24
    shapes: [
    [
      "path",
      {
        "d": "M10.733 5.076a10.744 10.744 0 0 1 11.205 6.575 1 1 0 0 1 0 .696 10.747 10.747 0 0 1-1.444 2.49",
      },
    ],
    [
      "path",
      {
        "d": "M14.084 14.158a3 3 0 0 1-4.242-4.242",
      },
    ],
    [
      "path",
      {
        "d": "M17.479 17.499a10.75 10.75 0 0 1-15.417-5.151 1 1 0 0 1 0-.696 10.75 10.75 0 0 1 4.446-5.143",
      },
    ],
    [
      "path",
      {
        "d": "m2 2 20 20",
      },
    ],
    ],
  },
  "EyeOpen": {
    // lucide/Eye — inks 20.0x14.0 of 24
    shapes: [
    [
      "path",
      {
        "d": "M2.062 12.348a1 1 0 0 1 0-.696 10.75 10.75 0 0 1 19.876 0 1 1 0 0 1 0 .696 10.75 10.75 0 0 1-19.876 0",
      },
    ],
    [
      "circle",
      {
        "cx": "12",
        "cy": "12",
        "r": "3",
      },
    ],
    ],
  },
  "FlowHorizontal": {
    // native — inks 18.0x18.0 of 24
    shapes: [
    [
      "path",
      {
        "d": "M5.25 3h3a2.25 2.25 0 0 1 2.25 2.25v3a2.25 2.25 0 0 1 -2.25 2.25h-3a2.25 2.25 0 0 1 -2.25 -2.25v-3a2.25 2.25 0 0 1 2.25 -2.25zM5.25 4.5h3a0.75 0.75 0 0 1 0.75 0.75v3a0.75 0.75 0 0 1 -0.75 0.75h-3a0.75 0.75 0 0 1 -0.75 -0.75v-3a0.75 0.75 0 0 1 0.75 -0.75z",
        "fill-rule": "evenodd",
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    [
      "path",
      {
        "d": "M15.75 3h3a2.25 2.25 0 0 1 2.25 2.25v3a2.25 2.25 0 0 1 -2.25 2.25h-3a2.25 2.25 0 0 1 -2.25 -2.25v-3a2.25 2.25 0 0 1 2.25 -2.25zM15.75 4.5h3a0.75 0.75 0 0 1 0.75 0.75v3a0.75 0.75 0 0 1 -0.75 0.75h-3a0.75 0.75 0 0 1 -0.75 -0.75v-3a0.75 0.75 0 0 1 0.75 -0.75z",
        "fill-rule": "evenodd",
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    [
      "rect",
      {
        "x": 3,
        "y": 16.5,
        "width": 16.5,
        "height": 1.5,
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    [
      "path",
      {
        "d": "M17.25 13.5L21 17.25L17.25 21L15.149999999999999 21L18.9 17.25L15.149999999999999 13.5z",
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    ],
  },
  "FlowNone": {
    // native — inks 18.0x18.0 of 24
    shapes: [
    [
      "path",
      {
        "d": "M5.25 3h3a2.25 2.25 0 0 1 2.25 2.25v3a2.25 2.25 0 0 1 -2.25 2.25h-3a2.25 2.25 0 0 1 -2.25 -2.25v-3a2.25 2.25 0 0 1 2.25 -2.25zM5.25 4.5h3a0.75 0.75 0 0 1 0.75 0.75v3a0.75 0.75 0 0 1 -0.75 0.75h-3a0.75 0.75 0 0 1 -0.75 -0.75v-3a0.75 0.75 0 0 1 0.75 -0.75z",
        "fill-rule": "evenodd",
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    [
      "path",
      {
        "d": "M15.75 9h3a2.25 2.25 0 0 1 2.25 2.25v3a2.25 2.25 0 0 1 -2.25 2.25h-3a2.25 2.25 0 0 1 -2.25 -2.25v-3a2.25 2.25 0 0 1 2.25 -2.25zM15.75 10.5h3a0.75 0.75 0 0 1 0.75 0.75v3a0.75 0.75 0 0 1 -0.75 0.75h-3a0.75 0.75 0 0 1 -0.75 -0.75v-3a0.75 0.75 0 0 1 0.75 -0.75z",
        "fill-rule": "evenodd",
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    [
      "path",
      {
        "d": "M5.25 13.5h3a2.25 2.25 0 0 1 2.25 2.25v3a2.25 2.25 0 0 1 -2.25 2.25h-3a2.25 2.25 0 0 1 -2.25 -2.25v-3a2.25 2.25 0 0 1 2.25 -2.25zM5.25 15h3a0.75 0.75 0 0 1 0.75 0.75v3a0.75 0.75 0 0 1 -0.75 0.75h-3a0.75 0.75 0 0 1 -0.75 -0.75v-3a0.75 0.75 0 0 1 0.75 -0.75z",
        "fill-rule": "evenodd",
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    ],
  },
  "FlowVertical": {
    // native — inks 18.0x18.0 of 24
    shapes: [
    [
      "path",
      {
        "d": "M5.25 3h3a2.25 2.25 0 0 1 2.25 2.25v3a2.25 2.25 0 0 1 -2.25 2.25h-3a2.25 2.25 0 0 1 -2.25 -2.25v-3a2.25 2.25 0 0 1 2.25 -2.25zM5.25 4.5h3a0.75 0.75 0 0 1 0.75 0.75v3a0.75 0.75 0 0 1 -0.75 0.75h-3a0.75 0.75 0 0 1 -0.75 -0.75v-3a0.75 0.75 0 0 1 0.75 -0.75z",
        "fill-rule": "evenodd",
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    [
      "path",
      {
        "d": "M5.25 13.5h3a2.25 2.25 0 0 1 2.25 2.25v3a2.25 2.25 0 0 1 -2.25 2.25h-3a2.25 2.25 0 0 1 -2.25 -2.25v-3a2.25 2.25 0 0 1 2.25 -2.25zM5.25 15h3a0.75 0.75 0 0 1 0.75 0.75v3a0.75 0.75 0 0 1 -0.75 0.75h-3a0.75 0.75 0 0 1 -0.75 -0.75v-3a0.75 0.75 0 0 1 0.75 -0.75z",
        "fill-rule": "evenodd",
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    [
      "rect",
      {
        "x": 16.5,
        "y": 3,
        "width": 1.5,
        "height": 16.5,
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    [
      "path",
      {
        "d": "M13.5 17.25L17.25 21L21 17.25L21 15.149999999999999L17.25 18.9L13.5 15.149999999999999z",
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    ],
  },
  "FlowWrap": {
    // native — inks 18.0x18.0 of 24
    shapes: [
    [
      "path",
      {
        "d": "M5.25 3h3a2.25 2.25 0 0 1 2.25 2.25v3a2.25 2.25 0 0 1 -2.25 2.25h-3a2.25 2.25 0 0 1 -2.25 -2.25v-3a2.25 2.25 0 0 1 2.25 -2.25zM5.25 4.5h3a0.75 0.75 0 0 1 0.75 0.75v3a0.75 0.75 0 0 1 -0.75 0.75h-3a0.75 0.75 0 0 1 -0.75 -0.75v-3a0.75 0.75 0 0 1 0.75 -0.75z",
        "fill-rule": "evenodd",
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    [
      "path",
      {
        "d": "M15.75 3h3a2.25 2.25 0 0 1 2.25 2.25v3a2.25 2.25 0 0 1 -2.25 2.25h-3a2.25 2.25 0 0 1 -2.25 -2.25v-3a2.25 2.25 0 0 1 2.25 -2.25zM15.75 4.5h3a0.75 0.75 0 0 1 0.75 0.75v3a0.75 0.75 0 0 1 -0.75 0.75h-3a0.75 0.75 0 0 1 -0.75 -0.75v-3a0.75 0.75 0 0 1 0.75 -0.75z",
        "fill-rule": "evenodd",
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    [
      "path",
      {
        "d": "M5.25 13.5h3a2.25 2.25 0 0 1 2.25 2.25v3a2.25 2.25 0 0 1 -2.25 2.25h-3a2.25 2.25 0 0 1 -2.25 -2.25v-3a2.25 2.25 0 0 1 2.25 -2.25zM5.25 15h3a0.75 0.75 0 0 1 0.75 0.75v3a0.75 0.75 0 0 1 -0.75 0.75h-3a0.75 0.75 0 0 1 -0.75 -0.75v-3a0.75 0.75 0 0 1 0.75 -0.75z",
        "fill-rule": "evenodd",
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    [
      "path",
      {
        "d": "M15.75 13.5h3a2.25 2.25 0 0 1 2.25 2.25v3a2.25 2.25 0 0 1 -2.25 2.25h-3a2.25 2.25 0 0 1 -2.25 -2.25v-3a2.25 2.25 0 0 1 2.25 -2.25zM15.75 15h3a0.75 0.75 0 0 1 0.75 0.75v3a0.75 0.75 0 0 1 -0.75 0.75h-3a0.75 0.75 0 0 1 -0.75 -0.75v-3a0.75 0.75 0 0 1 0.75 -0.75z",
        "fill-rule": "evenodd",
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    ],
  },
  "GapColumn": {
    // native — inks 18.0x15.0 of 24
    shapes: [
    [
      "rect",
      {
        "x": 3,
        "y": 4.5,
        "width": 3,
        "height": 15,
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    [
      "rect",
      {
        "x": 18,
        "y": 4.5,
        "width": 3,
        "height": 15,
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    [
      "rect",
      {
        "x": 9,
        "y": 10.5,
        "width": 1.5,
        "height": 3,
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    [
      "rect",
      {
        "x": 13.5,
        "y": 10.5,
        "width": 1.5,
        "height": 3,
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    ],
  },
  "GapRow": {
    // native — inks 15.0x18.0 of 24
    shapes: [
    [
      "rect",
      {
        "x": 4.5,
        "y": 3,
        "width": 15,
        "height": 3,
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    [
      "rect",
      {
        "x": 4.5,
        "y": 18,
        "width": 15,
        "height": 3,
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    [
      "rect",
      {
        "x": 10.5,
        "y": 9,
        "width": 3,
        "height": 1.5,
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    [
      "rect",
      {
        "x": 10.5,
        "y": 13.5,
        "width": 3,
        "height": 1.5,
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    ],
  },
  "Grid2x2": {
    // lucide/Grid2x2 — inks 18.0x18.0 of 24
    shapes: [
    [
      "path",
      {
        "d": "M12 3v18",
      },
    ],
    [
      "path",
      {
        "d": "M3 12h18",
      },
    ],
    [
      "rect",
      {
        "x": "3",
        "y": "3",
        "width": "18",
        "height": "18",
        "rx": "2",
      },
    ],
    ],
  },
  "Image": {
    // lucide/Image — inks 18.0x18.0 of 24
    shapes: [
    [
      "rect",
      {
        "width": "18",
        "height": "18",
        "x": "3",
        "y": "3",
        "rx": "2",
        "ry": "2",
      },
    ],
    [
      "circle",
      {
        "cx": "9",
        "cy": "9",
        "r": "2",
      },
    ],
    [
      "path",
      {
        "d": "m21 15-3.086-3.086a2 2 0 0 0-2.828 0L6 21",
      },
    ],
    ],
  },
  "Info": {
    // lucide/Info — inks 20.0x20.0 of 24
    shapes: [
    [
      "circle",
      {
        "cx": "12",
        "cy": "12",
        "r": "10",
      },
    ],
    [
      "path",
      {
        "d": "M12 16v-4",
      },
    ],
    [
      "path",
      {
        "d": "M12 8h.01",
      },
    ],
    ],
  },
  "InfoMark": {
    // lucide/Info — inks 0.0x12.0 of 24
    shapes: [
    [
      "path",
      {
        "d": "M12 18L12 12",
      },
    ],
    [
      "path",
      {
        "d": "M12 6L12.015 6",
      },
    ],
    ],
  },
  "ListChecks": {
    // lucide/ListChecks — inks 18.0x14.0 of 24
    shapes: [
    [
      "path",
      {
        "d": "M13 5h8",
      },
    ],
    [
      "path",
      {
        "d": "M13 12h8",
      },
    ],
    [
      "path",
      {
        "d": "M13 19h8",
      },
    ],
    [
      "path",
      {
        "d": "m3 17 2 2 4-4",
      },
    ],
    [
      "path",
      {
        "d": "m3 7 2 2 4-4",
      },
    ],
    ],
  },
  "Lock": {
    // lucide/Lock — inks 18.0x20.0 of 24
    shapes: [
    [
      "rect",
      {
        "width": "18",
        "height": "11",
        "x": "3",
        "y": "11",
        "rx": "2",
        "ry": "2",
      },
    ],
    [
      "path",
      {
        "d": "M7 11V7a5 5 0 0 1 10 0v4",
      },
    ],
    ],
  },
  "LockOpen": {
    // lucide/LockOpen — inks 18.0x20.0 of 24
    shapes: [
    [
      "rect",
      {
        "width": "18",
        "height": "11",
        "x": "3",
        "y": "11",
        "rx": "2",
        "ry": "2",
      },
    ],
    [
      "path",
      {
        "d": "M7 11V7a5 5 0 0 1 9.9-1",
      },
    ],
    ],
  },
  "MessageSquare": {
    // lucide/MessageCircle — inks 15.6x15.6 of 24
    shapes: [
    [
      "path",
      {
        "d": "M19.0262 15.3868A1.56 1.56 0 0 0 18.9529 16.297L19.7836 18.8632A0.78 0.78 0 0 1 18.8195 19.7743L16.1574 18.9958A1.56 1.56 0 0 0 15.3002 19.0676A7.8 7.8 0 1 1 19.0262 15.3868",
      },
    ],
    ],
  },
  "Minimize": {
    // lucide/Minimize — inks 18.0x18.0 of 24
    shapes: [
    [
      "path",
      {
        "d": "M8 3v3a2 2 0 0 1-2 2H3",
      },
    ],
    [
      "path",
      {
        "d": "M21 8h-3a2 2 0 0 1-2-2V3",
      },
    ],
    [
      "path",
      {
        "d": "M3 16h3a2 2 0 0 1 2 2v3",
      },
    ],
    [
      "path",
      {
        "d": "M16 21v-3a2 2 0 0 1 2-2h3",
      },
    ],
    ],
  },
  "Minus": {
    // lucide/Minus — inks 14.0x0.0 of 24
    shapes: [
    [
      "path",
      {
        "d": "M5 12h14",
      },
    ],
    ],
  },
  "Moon": {
    // native — inks 19.2x18.0 of 24
    shapes: [
    [
      "path",
      {
        "d": "M21.569723122116326 16.445230666635656A10.5 10.5 0 1 1 5.571558805248048 2.9950768545427424A12.299999999999999 12.299999999999999 0 0 0 21.569723122116326 16.445230666635656z",
        "fill-rule": "evenodd",
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    ],
  },
  "Opacity": {
    // native — inks 18.0x18.0 of 24
    shapes: [
    [
      "path",
      {
        "d": "M3 3h18v18h-18zM4.5 4.5h15v15h-15z",
        "fill-rule": "evenodd",
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    [
      "rect",
      {
        "x": 4.5,
        "y": 4.5,
        "width": 7.5,
        "height": 7.5,
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    [
      "rect",
      {
        "x": 12,
        "y": 12,
        "width": 7.5,
        "height": 7.5,
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    ],
  },
  "PadBottom": {
    // native — inks 18.0x18.0 of 24
    shapes: [
    [
      "path",
      {
        "d": "M3 3h18v18h-18zM4.5 4.5h15v15h-15z",
        "fill-rule": "evenodd",
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    [
      "rect",
      {
        "x": 3,
        "y": 18,
        "width": 18,
        "height": 3,
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    ],
  },
  "PadLeft": {
    // native — inks 18.0x18.0 of 24
    shapes: [
    [
      "path",
      {
        "d": "M3 3h18v18h-18zM4.5 4.5h15v15h-15z",
        "fill-rule": "evenodd",
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    [
      "rect",
      {
        "x": 3,
        "y": 3,
        "width": 3,
        "height": 18,
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    ],
  },
  "PadRight": {
    // native — inks 18.0x18.0 of 24
    shapes: [
    [
      "path",
      {
        "d": "M3 3h18v18h-18zM4.5 4.5h15v15h-15z",
        "fill-rule": "evenodd",
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    [
      "rect",
      {
        "x": 18,
        "y": 3,
        "width": 3,
        "height": 18,
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    ],
  },
  "PadTop": {
    // native — inks 18.0x18.0 of 24
    shapes: [
    [
      "path",
      {
        "d": "M3 3h18v18h-18zM4.5 4.5h15v15h-15z",
        "fill-rule": "evenodd",
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    [
      "rect",
      {
        "x": 3,
        "y": 3,
        "width": 18,
        "height": 3,
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    ],
  },
  "PanelLeft": {
    // native — inks 18.0x18.0 of 24
    shapes: [
    [
      "path",
      {
        "d": "M6.75 3h10.5a3.75 3.75 0 0 1 3.75 3.75v10.5a3.75 3.75 0 0 1 -3.75 3.75h-10.5a3.75 3.75 0 0 1 -3.75 -3.75v-10.5a3.75 3.75 0 0 1 3.75 -3.75zM6.75 5.25h10.5a1.5 1.5 0 0 1 1.5 1.5v10.5a1.5 1.5 0 0 1 -1.5 1.5h-10.5a1.5 1.5 0 0 1 -1.5 -1.5v-10.5a1.5 1.5 0 0 1 1.5 -1.5z",
        "fill-rule": "evenodd",
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    [
      "rect",
      {
        "x": 9,
        "y": 5.25,
        "width": 2.25,
        "height": 13.5,
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    ],
    // filled counterpart — inks 18.0x18.0 of 24
    filled: [
    [
      "path",
      {
        "d": "M6.75 3h10.5a3.75 3.75 0 0 1 3.75 3.75v10.5a3.75 3.75 0 0 1 -3.75 3.75h-10.5a3.75 3.75 0 0 1 -3.75 -3.75v-10.5a3.75 3.75 0 0 1 3.75 -3.75zM6.75 5.25h10.5a1.5 1.5 0 0 1 1.5 1.5v10.5a1.5 1.5 0 0 1 -1.5 1.5h-10.5a1.5 1.5 0 0 1 -1.5 -1.5v-10.5a1.5 1.5 0 0 1 1.5 -1.5z",
        "fill-rule": "evenodd",
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    [
      "path",
      {
        "d": "M6.75 5.25h4.5v13.5h-4.5a1.5 1.5 0 0 1 -1.5 -1.5v-10.5a1.5 1.5 0 0 1 1.5 -1.5z",
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    ],
  },
  "PanelRight": {
    // native — inks 18.0x18.0 of 24
    shapes: [
    [
      "path",
      {
        "d": "M6.75 3h10.5a3.75 3.75 0 0 1 3.75 3.75v10.5a3.75 3.75 0 0 1 -3.75 3.75h-10.5a3.75 3.75 0 0 1 -3.75 -3.75v-10.5a3.75 3.75 0 0 1 3.75 -3.75zM6.75 5.25h10.5a1.5 1.5 0 0 1 1.5 1.5v10.5a1.5 1.5 0 0 1 -1.5 1.5h-10.5a1.5 1.5 0 0 1 -1.5 -1.5v-10.5a1.5 1.5 0 0 1 1.5 -1.5z",
        "fill-rule": "evenodd",
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    [
      "rect",
      {
        "x": 12.75,
        "y": 5.25,
        "width": 2.25,
        "height": 13.5,
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    ],
    // filled counterpart — inks 18.0x18.0 of 24
    filled: [
    [
      "path",
      {
        "d": "M6.75 3h10.5a3.75 3.75 0 0 1 3.75 3.75v10.5a3.75 3.75 0 0 1 -3.75 3.75h-10.5a3.75 3.75 0 0 1 -3.75 -3.75v-10.5a3.75 3.75 0 0 1 3.75 -3.75zM6.75 5.25h10.5a1.5 1.5 0 0 1 1.5 1.5v10.5a1.5 1.5 0 0 1 -1.5 1.5h-10.5a1.5 1.5 0 0 1 -1.5 -1.5v-10.5a1.5 1.5 0 0 1 1.5 -1.5z",
        "fill-rule": "evenodd",
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    [
      "path",
      {
        "d": "M12.75 5.25h4.5a1.5 1.5 0 0 1 1.5 1.5v10.5a1.5 1.5 0 0 1 -1.5 1.5h-4.5z",
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    ],
  },
  "Pencil": {
    // lucide/Pencil — inks 20.0x20.0 of 24
    shapes: [
    [
      "path",
      {
        "d": "M21.174 6.812a1 1 0 0 0-3.986-3.987L3.842 16.174a2 2 0 0 0-.5.83l-1.321 4.352a.5.5 0 0 0 .623.622l4.353-1.32a2 2 0 0 0 .83-.497z",
      },
    ],
    [
      "path",
      {
        "d": "m15 5 4 4",
      },
    ],
    ],
  },
  "Play": {
    // lucide/Play — inks 16.0x18.0 of 24
    shapes: [
    [
      "path",
      {
        "d": "M5 5a2 2 0 0 1 3.008-1.728l11.997 6.998a2 2 0 0 1 .003 3.458l-12 7A2 2 0 0 1 5 19z",
      },
    ],
    ],
  },
  "Plus": {
    // lucide/Plus — inks 14.0x14.0 of 24
    shapes: [
    [
      "path",
      {
        "d": "M5 12h14",
      },
    ],
    [
      "path",
      {
        "d": "M12 5v14",
      },
    ],
    ],
  },
  "Search": {
    // lucide/Search — inks 18.0x18.0 of 24
    shapes: [
    [
      "path",
      {
        "d": "m21 21-4.34-4.34",
      },
    ],
    [
      "circle",
      {
        "cx": "11",
        "cy": "11",
        "r": "8",
      },
    ],
    ],
  },
  "Send": {
    // lucide/Send — inks 20.0x20.0 of 24
    shapes: [
    [
      "path",
      {
        "d": "M14.536 21.686a.5.5 0 0 0 .937-.024l6.5-19a.496.496 0 0 0-.635-.635l-19 6.5a.5.5 0 0 0-.024.937l7.93 3.18a2 2 0 0 1 1.112 1.11z",
      },
    ],
    [
      "path",
      {
        "d": "m21.854 2.147-10.94 10.939",
      },
    ],
    ],
  },
  "SpaceBetweenHorizontal": {
    // native — inks 18.0x18.0 of 24
    shapes: [
    [
      "rect",
      {
        "x": 3,
        "y": 3,
        "width": 3,
        "height": 18,
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    [
      "rect",
      {
        "x": 18,
        "y": 3,
        "width": 3,
        "height": 18,
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    [
      "rect",
      {
        "x": 9,
        "y": 10.5,
        "width": 6,
        "height": 3,
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    ],
  },
  "SpaceBetweenVertical": {
    // native — inks 18.0x18.0 of 24
    shapes: [
    [
      "rect",
      {
        "x": 3,
        "y": 3,
        "width": 18,
        "height": 3,
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    [
      "rect",
      {
        "x": 3,
        "y": 18,
        "width": 18,
        "height": 3,
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    [
      "rect",
      {
        "x": 10.5,
        "y": 9,
        "width": 3,
        "height": 6,
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    ],
  },
  "Sparkles": {
    // lucide/Sparkles — inks 20.0x20.0 of 24
    shapes: [
    [
      "path",
      {
        "d": "M11.017 2.814a1 1 0 0 1 1.966 0l1.051 5.558a2 2 0 0 0 1.594 1.594l5.558 1.051a1 1 0 0 1 0 1.966l-5.558 1.051a2 2 0 0 0-1.594 1.594l-1.051 5.558a1 1 0 0 1-1.966 0l-1.051-5.558a2 2 0 0 0-1.594-1.594l-5.558-1.051a1 1 0 0 1 0-1.966l5.558-1.051a2 2 0 0 0 1.594-1.594z",
      },
    ],
    [
      "path",
      {
        "d": "M20 2v4",
      },
    ],
    [
      "path",
      {
        "d": "M22 4h-4",
      },
    ],
    [
      "circle",
      {
        "cx": "4",
        "cy": "20",
        "r": "2",
      },
    ],
    ],
  },
  "Square": {
    // lucide/Square — inks 18.0x18.0 of 24
    shapes: [
    [
      "rect",
      {
        "width": "18",
        "height": "18",
        "x": "3",
        "y": "3",
        "rx": "2",
      },
    ],
    ],
  },
  "Sun": {
    // native — inks 18.8x18.8 of 24
    shapes: [
    [
      "circle",
      {
        "cx": 11.625,
        "cy": 11.625,
        "r": 4.875,
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    [
      "rect",
      {
        "x": 10.5,
        "y": 2.25,
        "width": 2.25,
        "height": 3,
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    [
      "rect",
      {
        "x": 10.5,
        "y": 18,
        "width": 2.25,
        "height": 3,
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    [
      "rect",
      {
        "x": 2.25,
        "y": 10.5,
        "width": 3,
        "height": 2.25,
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    [
      "rect",
      {
        "x": 18,
        "y": 10.5,
        "width": 3,
        "height": 2.25,
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    [
      "path",
      {
        "d": "M4.995 3.4040097423302678L7.1175 5.526509742330268L7.1175 8.708490257669734L4.995 6.585990257669732z",
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    [
      "path",
      {
        "d": "M16.1325 14.54150974233027L18.255 16.66400974233027L18.255 19.845990257669733L16.1325 17.72349025766973z",
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    [
      "path",
      {
        "d": "M18.255 3.4040097423302678L16.1325 5.526509742330268L16.1325 8.708490257669734L18.255 6.585990257669732z",
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    [
      "path",
      {
        "d": "M7.1175 14.54150974233027L4.995 16.66400974233027L4.995 19.845990257669733L7.1175 17.72349025766973z",
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    ],
  },
  "TextAlignBottom": {
    // native — inks 18.0x18.0 of 24
    shapes: [
    [
      "rect",
      {
        "x": 3,
        "y": 19.5,
        "width": 18,
        "height": 1.5,
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    [
      "rect",
      {
        "x": 10.5,
        "y": 3,
        "width": 1.5,
        "height": 15,
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    [
      "path",
      {
        "d": "M6.75 13.5L11.25 18L15.75 13.5L15.75 11.399999999999999L11.25 15.899999999999999L6.75 11.399999999999999z",
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    ],
  },
  "TextAlignCenter": {
    // native — inks 18.0x13.5 of 24
    shapes: [
    [
      "rect",
      {
        "x": 3,
        "y": 4.5,
        "width": 18,
        "height": 1.5,
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    [
      "rect",
      {
        "x": 6,
        "y": 10.5,
        "width": 12,
        "height": 1.5,
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    [
      "rect",
      {
        "x": 4.5,
        "y": 16.5,
        "width": 15,
        "height": 1.5,
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    ],
  },
  "TextAlignJustify": {
    // native — inks 18.0x13.5 of 24
    shapes: [
    [
      "rect",
      {
        "x": 3,
        "y": 4.5,
        "width": 18,
        "height": 1.5,
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    [
      "rect",
      {
        "x": 3,
        "y": 10.5,
        "width": 18,
        "height": 1.5,
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    [
      "rect",
      {
        "x": 3,
        "y": 16.5,
        "width": 18,
        "height": 1.5,
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    ],
  },
  "TextAlignLeft": {
    // native — inks 18.0x13.5 of 24
    shapes: [
    [
      "rect",
      {
        "x": 3,
        "y": 4.5,
        "width": 18,
        "height": 1.5,
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    [
      "rect",
      {
        "x": 3,
        "y": 10.5,
        "width": 12,
        "height": 1.5,
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    [
      "rect",
      {
        "x": 3,
        "y": 16.5,
        "width": 15,
        "height": 1.5,
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    ],
  },
  "TextAlignMiddle": {
    // native — inks 18.0x18.6 of 24
    shapes: [
    [
      "rect",
      {
        "x": 3,
        "y": 10.5,
        "width": 18,
        "height": 1.5,
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    [
      "rect",
      {
        "x": 10.5,
        "y": 3,
        "width": 1.5,
        "height": 6,
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    [
      "path",
      {
        "d": "M6.75 4.5L11.25 9L15.75 4.5L15.75 2.3999999999999995L11.25 6.8999999999999995L6.75 2.3999999999999995z",
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    [
      "rect",
      {
        "x": 10.5,
        "y": 15,
        "width": 1.5,
        "height": 6,
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    [
      "path",
      {
        "d": "M6.75 18L11.25 13.5L15.75 18L15.75 20.1L11.25 15.600000000000001L6.75 20.1z",
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    ],
  },
  "TextAlignRight": {
    // native — inks 18.0x13.5 of 24
    shapes: [
    [
      "rect",
      {
        "x": 3,
        "y": 4.5,
        "width": 18,
        "height": 1.5,
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    [
      "rect",
      {
        "x": 9,
        "y": 10.5,
        "width": 12,
        "height": 1.5,
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    [
      "rect",
      {
        "x": 6,
        "y": 16.5,
        "width": 15,
        "height": 1.5,
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    ],
  },
  "TextAlignTop": {
    // native — inks 18.0x18.0 of 24
    shapes: [
    [
      "rect",
      {
        "x": 3,
        "y": 3,
        "width": 18,
        "height": 1.5,
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    [
      "rect",
      {
        "x": 10.5,
        "y": 6,
        "width": 1.5,
        "height": 15,
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    [
      "path",
      {
        "d": "M6.75 10.5L11.25 6L15.75 10.5L15.75 12.600000000000001L11.25 8.100000000000001L6.75 12.600000000000001z",
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    ],
  },
  "ToolClose": {
    // native — inks 15.1x15.1 of 24
    shapes: [
    [
      "path",
      {
        "d": "M4.800000000000001 4.800000000000001A1.1249999999999998 1.1249999999999998 0 0 0 4.800000000000001 6.390990257669731L17.609009742330265 19.200000000000003A1.125 1.125 0 0 0 19.200000000000003 19.200000000000003L19.200000000000003 19.200000000000003A1.125 1.125 0 0 0 19.200000000000003 17.609009742330265L6.390990257669731 4.800000000000001A1.1249999999999998 1.1249999999999998 0 0 0 4.800000000000001 4.800000000000001L4.800000000000001 4.800000000000001z",
        "fill-rule": "evenodd",
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    [
      "path",
      {
        "d": "M4.800000000000001 19.200000000000003A1.1249999999999996 1.1249999999999996 0 0 0 6.390990257669731 19.200000000000003L19.200000000000003 6.390990257669731A1.1249999999999996 1.1249999999999996 0 0 0 19.200000000000003 4.800000000000001L19.200000000000003 4.799999999999999A1.125 1.125 0 0 0 17.60900974233027 4.800000000000001L4.800000000000001 17.60900974233027A1.125 1.125 0 0 0 4.799999999999999 19.200000000000003L4.800000000000001 19.200000000000003z",
        "fill-rule": "evenodd",
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    ],
  },
  "ToolRedo": {
    // native — inks 17.3x18.0 of 24
    shapes: [
    [
      "path",
      {
        "d": "M16.125 3L20.25 7.125L16.125 11.25L12.943019484660537 11.25L17.06801948466054 7.125L12.943019484660537 3z",
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    [
      "rect",
      {
        "x": 10.5,
        "y": 6,
        "width": 9,
        "height": 2.25,
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    [
      "path",
      {
        "d": "M10.5 21A7.5 7.5 0 0 1 10.5 6L10.5 8.25A5.25 5.25 0 0 0 10.5 18.75z",
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    [
      "rect",
      {
        "x": 10.5,
        "y": 18.75,
        "width": 4.5,
        "height": 2.25,
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    ],
  },
  "ToolUndo": {
    // native — inks 17.3x18.0 of 24
    shapes: [
    [
      "path",
      {
        "d": "M7.875 3L3.75 7.125L7.875 11.25L11.056980515339465 11.25L6.931980515339465 7.125L11.056980515339465 3z",
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    [
      "rect",
      {
        "x": 4.5,
        "y": 6,
        "width": 9,
        "height": 2.25,
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    [
      "path",
      {
        "d": "M13.5 6A7.5 7.5 0 0 1 13.5 21L13.5 18.75A5.25 5.25 0 0 0 13.5 8.25z",
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    [
      "rect",
      {
        "x": 9,
        "y": 18.75,
        "width": 4.5,
        "height": 2.25,
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    ],
  },
  "Trash": {
    // lucide/Trash2 — inks 18.0x20.0 of 24
    shapes: [
    [
      "path",
      {
        "d": "M10 11v6",
      },
    ],
    [
      "path",
      {
        "d": "M14 11v6",
      },
    ],
    [
      "path",
      {
        "d": "M19 6v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6",
      },
    ],
    [
      "path",
      {
        "d": "M3 6h18",
      },
    ],
    [
      "path",
      {
        "d": "M8 6V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2",
      },
    ],
    ],
  },
  "Type": {
    // lucide/Type — inks 16.0x16.0 of 24
    shapes: [
    [
      "path",
      {
        "d": "M12 4v16",
      },
    ],
    [
      "path",
      {
        "d": "M4 7V5a1 1 0 0 1 1-1h14a1 1 0 0 1 1 1v2",
      },
    ],
    [
      "path",
      {
        "d": "M9 20h6",
      },
    ],
    ],
  },
  "WrapText": {
    // lucide/WrapText — inks 18.0x17.0 of 24
    shapes: [
    [
      "path",
      {
        "d": "m16 16-3 3 3 3",
      },
    ],
    [
      "path",
      {
        "d": "M3 12h14.5a1 1 0 0 1 0 7H13",
      },
    ],
    [
      "path",
      {
        "d": "M3 19h6",
      },
    ],
    [
      "path",
      {
        "d": "M3 5h18",
      },
    ],
    ],
  },
  "X": {
    // lucide/X — inks 12.0x12.0 of 24
    shapes: [
    [
      "path",
      {
        "d": "M18 6 6 18",
      },
    ],
    [
      "path",
      {
        "d": "m6 6 12 12",
      },
    ],
    ],
  },
} as const satisfies Record<string, IconData>

export type IconName = keyof typeof ICONS

export const ICON_NAMES = Object.keys(ICONS) as IconName[]

/**
 * The glyphs authored on the native 16 lattice rather than taken from Lucide.
 *
 * Exported so the rung rule can be CHECKED rather than just written down: these
 * land on whole device pixels only at a size that is a multiple of 8, so they
 * may be drawn at `icon.control` (16) and above, never at `icon.row` (12) or
 * `icon.mark` (10). `test/icon-cases.mjs` reads this list and greps the source
 * for a call that breaks it.
 *
 * A comment could not carry this. The mistake it prevents — reaching for
 * `tokens.icon.row` because the text beside the glyph is 12px — is locally
 * reasonable every single time, and the result looks fine until it is set
 * beside a glyph drawn at 16.
 */
export const NATIVE_ICON_NAMES = ["AlignCenterHorizontal","AlignCenterVertical","AlignEndHorizontal","AlignEndVertical","AlignStartHorizontal","AlignStartVertical","ArrangeBack","ArrangeBackward","ArrangeForward","ArrangeFront","CornerRadius","Cursor","FlowHorizontal","FlowNone","FlowVertical","FlowWrap","GapColumn","GapRow","Moon","Opacity","PadBottom","PadLeft","PadRight","PadTop","PanelLeft","PanelRight","SpaceBetweenHorizontal","SpaceBetweenVertical","Sun","TextAlignBottom","TextAlignCenter","TextAlignJustify","TextAlignLeft","TextAlignMiddle","TextAlignRight","TextAlignTop","ToolClose","ToolRedo","ToolUndo"] as const satisfies readonly IconName[]

/** The rungs a native glyph renders crisply at — every multiple of 8 on the ramp. */
export const NATIVE_ICON_SIZES = [16, 24, 32] as const satisfies readonly IconSize[]

const SVG_NS = "http://www.w3.org/2000/svg"

function build(node: IconNode): SVGElement {
  const [tag, attrs, children] = node
  const element = document.createElementNS(SVG_NS, tag)
  for (const [key, value] of Object.entries(attrs)) element.setAttribute(key, String(value))
  for (const child of children ?? []) element.append(build(child))
  return element
}

/**
 * Draw one glyph from its data.
 *
 * Exported so the host's own icon set — served by the loopback `/icons` route
 * and offered as variants in the inspector — is drawn by the same rules as
 * these. Two renderers would be two answers to "how big is a glyph", and only
 * one of them would be right.
 */
export function drawIcon(data: IconData, size: IconSize = 16, weight: IconWeight = "auto"): SVGSVGElement {
  const svg = document.createElementNS(SVG_NS, "svg")
  svg.setAttribute("width", String(size))
  svg.setAttribute("height", String(size))
  svg.setAttribute("viewBox", "0 0 24 24")
  // The fill is opt-in and the outline is what `auto` means: a flood reads only
  // on a closed silhouette, so a caller asks for it knowing which mark it holds.
  svg.setAttribute("fill", weight === "filled" ? "currentColor" : "none")
  svg.setAttribute("stroke", "currentColor")
  const stroke = STROKE_FOR_SIZE[size]
  svg.setAttribute("stroke-width", String(stroke))
  svg.style.setProperty(ICON_STROKE_VARIABLE, String(stroke))
  svg.setAttribute("stroke-linecap", "round")
  svg.setAttribute("stroke-linejoin", "round")
  svg.setAttribute(ICON_MARKER_ATTRIBUTE, "")
  svg.setAttribute("aria-hidden", "true")
  // The counterpart when the glyph has one, its own shapes otherwise. A mark
  // whose runs are all open floods to nothing, and a toggle drawing it would
  // report the same picture in both states.
  const shapes = weight === "filled" && data.filled ? data.filled : data.shapes
  for (const node of shapes) svg.append(build(node))
  return svg
}

/**
 * One glyph, sized and decorative.
 *
 * Colour comes from `currentColor`, never a token: the same mark is drawn on a
 * rest row, a hovered row and a filled selected row, and only the caller knows
 * which.
 */
export function icon(name: IconName, size: IconSize = 16, weight: IconWeight = "auto"): SVGSVGElement {
  const svg = drawIcon(ICONS[name], size, weight)
  /*
   * THE MARKER CARRIES THE NAME NOW, where it used to carry an empty string.
   *
   * Every rule that reads it is written `svg[data-de-glyph]`, which matches on
   * presence and is unaffected. What the value adds is the ability to say
   * something about ONE mark — and there is exactly one thing worth saying,
   * which is the optical correction for `Cursor` in `css/icons.ts`.
   *
   * Set here and not in `drawIcon`, because `drawIcon` also renders the HOST
   * app's own icons, whose names belong to a set this package did not author. A
   * rule written against one of ours must not be able to reach one of theirs.
   */
  svg.setAttribute(ICON_MARKER_ATTRIBUTE, name)
  return svg
}

/**
 * A glyph from the HOST's own icon set, which is a different set of rules.
 *
 * The app being edited ships its own icons, served by the loopback `/icons`
 * route so the inspector can offer one in place of another. Those are drawn the
 * way their author drew them: one weight, whatever grid and stroke they use,
 * nothing normalised. They must not be squeezed into the chrome's shape — this
 * editor does not get to decide that someone else's icon is a stroke family, or
 * to re-window a glyph it is about to write into their source. A second, smaller
 * renderer is the honest way to say that.
 */
export interface HostIconData {
  nodes: IconNode[]
  rootFill: string
  rootStroke?: string
}

export function drawHostIcon(data: HostIconData, size: IconSize = 16): SVGSVGElement {
  const svg = document.createElementNS(SVG_NS, "svg")
  svg.setAttribute("width", String(size))
  svg.setAttribute("height", String(size))
  svg.setAttribute("viewBox", "0 0 24 24")
  svg.setAttribute("fill", data.rootFill === "none" ? "none" : "currentColor")
  if (data.rootStroke) {
    svg.setAttribute("stroke", "currentColor")
    svg.setAttribute("stroke-width", "2")
    svg.setAttribute("stroke-linecap", "round")
    svg.setAttribute("stroke-linejoin", "round")
  }
  svg.setAttribute("aria-hidden", "true")
  for (const node of data.nodes) svg.append(build(node))
  return svg
}
