/**
 * The editor chrome's glyph set.
 *
 * GENERATED by `tools/build-icons.mjs` — do not hand-edit. To swap a glyph,
 * change the mapping in that script and re-run it. Sources, in order of
 * preference: the design foundations kit (`tools/icons/foundations`, 18
 * drawings) for every role the kit has a glyph for; Lucide 1.46.0
 * (https://lucide.dev/icons, ISC) for the editor's own subjects; and a native
 * lattice family authored in the script.
 *
 * Every glyph sits on one 24x24 grid, and four things follow, each of which
 * used to be the opposite here:
 *
 *   - ONE drawing per glyph, with a fill painted over it rather than a second
 *     drawing. Lucide ships no filled counterparts, and flooding an outline
 *     with `currentColor` reads only for a closed silhouette — but every mark a
 *     TOGGLE in this chrome draws is closed, so the pointer, the bubble and the
 *     layer stack all fill correctly from their own paths and cannot drift in
 *     size from the outline they replace. A row or a tab that reports itself
 *     `aria-selected` still gets the heavier stroke from the stylesheet (see
 *     `css/icons.ts`), because a list has its neighbours on screen to be
 *     compared against and a lone toolbar button does not.
 *
 *   - A `filled` array, on the few glyphs a flood cannot serve. A mark made
 *     only of open runs has no area to flood — `SlidersHorizontal` came out
 *     identical in both states — so those carry an authored counterpart, held
 *     by the generator to the same ink extent as their outline.
 *
 *   - NO per-glyph window. Nothing is re-fitted by widening its viewBox: that
 *     scales a stroke along with the drawing and lands it under weight, trading
 *     a size error for a weight error. The extents are deliberately uneven — a
 *     chevron inks 12 of the grid and a layer stack 20 — because that is
 *     each source's own optical sizing.
 *
 *   - ONE stroke width, the kit's 2, at every size. The kit's filled glyphs
 *     carry that weight baked into their outlines, so a stroke compensated per
 *     size would split the family at the small rungs. See `STROKE_FOR_SIZE`.
 */

export type IconNode = [
  tag: string,
  attrs: Record<string, string | number>,
  children?: IconNode[],
]

/**
 * One glyph: its shapes, on the shared 24 grid. A shape with `stroke: none` is
 * a fill whose weight is its outline; every other shape strokes at the root's
 * width.
 *
 * `filled` is the counterpart drawn for the marks a flood cannot express — see
 * the header. Absent, which is the usual case, the filled weight paints the
 * same shapes with `currentColor`, so the two states cannot be different marks.
 */
export interface IconData {
  shapes: IconNode[]
  filled?: IconNode[]
}

/**
 * Which weight a glyph is asked for.
 *
 * `auto` is the outline, and lets the stylesheet add the extra stroke when the
 * control reports itself selected in a list of its peers — which is how "on
 * means heavier" stays one rule rather than 79 call sites.
 *
 * `filled` is what a TOGGLE asks for while it is on. A stroke half a unit
 * heavier is a relative signal: legible beside the same glyph in its off state,
 * and unreadable on a button sitting on its own, which is exactly the case a
 * mode indicator has to answer. Solid or hollow needs nothing to compare
 * against.
 */
export type IconWeight = "outline" | "filled" | "auto"

/**
 * The only sizes a glyph may be drawn at: the kit's six icon roles in
 * `tokens.icon` — marker 12, inline 14, action 16, chrome 18, header 20,
 * feature 24.
 *
 * A union rather than `number`, so a size off the ramp fails to compile instead
 * of shipping. The set drifted to seven sizes once — 10, 12, 13, 14, 16, 18 and
 * 20, each added at one call site by someone reaching for the value that looked
 * right next to the text beside it. Nothing caught it, because every one of
 * those calls was locally reasonable.
 *
 * Call sites should pass `tokens.icon.action` and friends rather than the number,
 * which is what makes the ramp readable at the point of use; this type is the
 * backstop for the ones that do not.
 */
export type IconSize = 12 | 14 | 16 | 18 | 20 | 24

/**
 * The stroke each rung wears, in grid units: the kit's 2 at every rung.
 *
 * It used to be compensated per size, heavier on the small rungs. Two things
 * retired that. The kit's filled glyphs — chevron-down, x, copy, arrow-up —
 * carry a 2-unit weight baked into their outlines that no attribute can
 * thicken, so compensating the stroked half would split the set at exactly
 * the rungs where the two halves sit side by side. And the rung that needed
 * rescuing is gone: at the kit's floor of 12px, 2 units is exactly 1 CSS pixel,
 * two whole device pixels at 2x. Rendered thickness rises 1.0 to 2.0px across
 * the ramp — the same mark enlarged.
 *
 * `tools/build-icons.mjs` measures every stroked shape's clearance inside the
 * grid and fails the build if the heaviest stroke that renders would clip one.
 */
const STROKE_FOR_SIZE: Record<IconSize, number> = {
  12: 2,
  14: 2,
  16: 2,
  18: 2,
  20: 2,
  24: 2,
}

/**
 * The stroke width, published as a custom property the stylesheet can build on.
 *
 * Written ALONGSIDE the `stroke-width` attribute rather than instead of it. The
 * attribute is the value that is always right, including with no stylesheet at
 * all; the property is what lets one CSS rule say "pressed is half a unit
 * heavier" without knowing which rung the glyph was drawn at.
 */
export const ICON_STROKE_VARIABLE = "--de-icon-stroke"

/**
 * What marks an `<svg>` as one of OURS.
 *
 * The state rule in `css/icons.ts` leans on the custom property above, and
 * without this it would also reach two kinds of `<svg>` it has no business
 * restyling: the host's own icons, which `drawHostIcon` renders inside the
 * inspector exactly as their author drew them, and any `<svg>` the app being
 * edited happens to place inside a selected row. Both would pick up the
 * property's fallback and get re-weighted on selection — the editor quietly
 * redrawing someone else's artwork.
 */
export const ICON_MARKER_ATTRIBUTE = "data-de-glyph"

const ICONS = {
  "AlignCenterHorizontal": {
    // native — inks 18.0x16.5 of 24
    shapes: [
    [
      "rect",
      {
        "x": 3,
        "y": 10.5,
        "width": 18,
        "height": 1.5,
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    [
      "rect",
      {
        "x": 7.5,
        "y": 3,
        "width": 3,
        "height": 16.5,
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    [
      "rect",
      {
        "x": 13.5,
        "y": 6,
        "width": 3,
        "height": 10.5,
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    ],
  },
  "AlignCenterVertical": {
    // native — inks 16.5x18.0 of 24
    shapes: [
    [
      "rect",
      {
        "x": 10.5,
        "y": 3,
        "width": 1.5,
        "height": 18,
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    [
      "rect",
      {
        "x": 3,
        "y": 7.5,
        "width": 16.5,
        "height": 3,
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    [
      "rect",
      {
        "x": 6,
        "y": 13.5,
        "width": 10.5,
        "height": 3,
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    ],
  },
  "AlignEndHorizontal": {
    // native — inks 18.0x18.0 of 24
    shapes: [
    [
      "rect",
      {
        "x": 3,
        "y": 19.5,
        "width": 18,
        "height": 1.5,
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    [
      "rect",
      {
        "x": 7.5,
        "y": 3,
        "width": 3,
        "height": 13.5,
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    [
      "rect",
      {
        "x": 13.5,
        "y": 9,
        "width": 3,
        "height": 7.5,
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    ],
  },
  "AlignEndVertical": {
    // native — inks 18.0x18.0 of 24
    shapes: [
    [
      "rect",
      {
        "x": 19.5,
        "y": 3,
        "width": 1.5,
        "height": 18,
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    [
      "rect",
      {
        "x": 3,
        "y": 7.5,
        "width": 13.5,
        "height": 3,
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    [
      "rect",
      {
        "x": 9,
        "y": 13.5,
        "width": 7.5,
        "height": 3,
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    ],
  },
  "AlignStartHorizontal": {
    // native — inks 18.0x18.0 of 24
    shapes: [
    [
      "rect",
      {
        "x": 3,
        "y": 3,
        "width": 18,
        "height": 1.5,
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    [
      "rect",
      {
        "x": 7.5,
        "y": 7.5,
        "width": 3,
        "height": 13.5,
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    [
      "rect",
      {
        "x": 13.5,
        "y": 7.5,
        "width": 3,
        "height": 7.5,
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    ],
  },
  "AlignStartVertical": {
    // native — inks 18.0x18.0 of 24
    shapes: [
    [
      "rect",
      {
        "x": 3,
        "y": 3,
        "width": 1.5,
        "height": 18,
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    [
      "rect",
      {
        "x": 7.5,
        "y": 7.5,
        "width": 13.5,
        "height": 3,
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    [
      "rect",
      {
        "x": 7.5,
        "y": 13.5,
        "width": 7.5,
        "height": 3,
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    ],
  },
  "ArrangeBack": {
    // native — inks 18.0x18.0 of 24
    shapes: [
    [
      "rect",
      {
        "x": 3,
        "y": 19.5,
        "width": 18,
        "height": 1.5,
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    [
      "rect",
      {
        "x": 10.5,
        "y": 3,
        "width": 1.5,
        "height": 14.25,
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    [
      "path",
      {
        "d": "M6.75 12.75L11.25 17.25L15.75 12.75L15.75 10.649999999999999L11.25 15.149999999999999L6.75 10.649999999999999z",
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    ],
  },
  "ArrangeBackward": {
    // native — inks 9.0x16.5 of 24
    shapes: [
    [
      "rect",
      {
        "x": 10.5,
        "y": 3,
        "width": 1.5,
        "height": 16.5,
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    [
      "path",
      {
        "d": "M6.75 15L11.25 19.5L15.75 15L15.75 12.899999999999999L11.25 17.4L6.75 12.899999999999999z",
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    ],
  },
  "ArrangeForward": {
    // native — inks 9.0x16.5 of 24
    shapes: [
    [
      "rect",
      {
        "x": 10.5,
        "y": 4.5,
        "width": 1.5,
        "height": 16.5,
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    [
      "path",
      {
        "d": "M6.75 9L11.25 4.5L15.75 9L15.75 11.100000000000001L11.25 6.6000000000000005L6.75 11.100000000000001z",
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    ],
  },
  "ArrangeFront": {
    // native — inks 18.0x18.0 of 24
    shapes: [
    [
      "rect",
      {
        "x": 3,
        "y": 3,
        "width": 18,
        "height": 1.5,
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    [
      "rect",
      {
        "x": 10.5,
        "y": 6.75,
        "width": 1.5,
        "height": 14.25,
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    [
      "path",
      {
        "d": "M6.75 11.25L11.25 6.75L15.75 11.25L15.75 13.350000000000001L11.25 8.850000000000001L6.75 13.350000000000001z",
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    ],
  },
  "ArrowDown": {
    // foundations/arrow-up, fitted ×0.909 — inks 14.5x20.0 of 24
    shapes: [
    [
      "path",
      {
        "d": "M19.0064 15.37L12.6427 21.7336A0.9082 0.9082 0 0 1 11.6518 21.93A0.9073 0.9073 0 0 1 11.3564 21.7327L4.9927 15.37A0.9091 0.9091 0 1 1 6.2791 14.0845L11.0909 18.8964L11.0909 2.9091A0.9091 0.9091 0 1 1 12.9091 2.9091L12.9091 18.8964L17.7209 14.0845A0.9064 0.9064 0 0 1 19.0064 14.0845A0.9091 0.9091 0 0 1 19.0064 15.37z",
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    ],
  },
  "ArrowDownToLine": {
    // lucide/ArrowDownToLine — inks 14.0x18.0 of 24
    shapes: [
    [
      "path",
      {
        "d": "M12 17V3",
      },
    ],
    [
      "path",
      {
        "d": "m6 11 6 6 6-6",
      },
    ],
    [
      "path",
      {
        "d": "M19 21H5",
      },
    ],
    ],
  },
  "ArrowRight": {
    // foundations/arrow-right, fitted ×0.909 — inks 20.0x14.6 of 24
    shapes: [
    [
      "path",
      {
        "d": "M21.93 12.3473A0.91 0.91 0 0 0 21.7336 11.3564L15.37 4.9936A0.9091 0.9091 0 1 0 14.0845 6.2791L18.8964 11.0909L2.9091 11.0909A0.9091 0.9091 0 1 0 2.9091 12.9091L18.8964 12.9091L14.0845 17.7209A0.9091 0.9091 0 1 0 15.37 19.0064L21.7336 12.6427A0.9082 0.9082 0 0 0 21.93 12.3473z",
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    ],
  },
  "ArrowUp": {
    // foundations/arrow-up, fitted ×0.909 — inks 14.5x20.0 of 24
    shapes: [
    [
      "path",
      {
        "d": "M19.0064 8.63L12.6427 2.2664A0.9082 0.9082 0 0 0 11.6518 2.07A0.9073 0.9073 0 0 0 11.3564 2.2673L4.9927 8.63A0.9091 0.9091 0 1 0 6.2791 9.9155L11.0909 5.1036L11.0909 21.0909A0.9091 0.9091 0 1 0 12.9091 21.0909L12.9091 5.1036L17.7209 9.9155A0.9064 0.9064 0 0 0 19.0064 9.9155A0.9091 0.9091 0 0 0 19.0064 8.63z",
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    ],
  },
  "ArrowUpToLine": {
    // lucide/ArrowUpToLine — inks 14.0x18.0 of 24
    shapes: [
    [
      "path",
      {
        "d": "M5 3h14",
      },
    ],
    [
      "path",
      {
        "d": "m18 13-6-6-6 6",
      },
    ],
    [
      "path",
      {
        "d": "M12 7v14",
      },
    ],
    ],
  },
  "Ban": {
    // lucide/Ban — inks 20.0x20.0 of 24
    shapes: [
    [
      "circle",
      {
        "cx": "12",
        "cy": "12",
        "r": "10",
      },
    ],
    [
      "path",
      {
        "d": "M4.929 4.929 19.07 19.071",
      },
    ],
    ],
  },
  "Check": {
    // foundations/check, fitted ×0.909 — inks 18.2x11.8 of 24
    shapes: [
    [
      "path",
      {
        "d": "M21.0909 5.6364L9.2745 17.4527L2.9136 11.0945",
      },
    ],
    ],
  },
  "ChevronDown": {
    // lucide/ChevronDown — inks 12.0x6.0 of 24
    shapes: [
    [
      "path",
      {
        "d": "m6 9 6 6 6-6",
      },
    ],
    ],
  },
  "ChevronRight": {
    // lucide/ChevronRight — inks 6.0x12.0 of 24
    shapes: [
    [
      "path",
      {
        "d": "m9 18 6-6-6-6",
      },
    ],
    ],
  },
  "ChevronsDownUp": {
    // lucide/ChevronsDownUp — inks 10.0x16.0 of 24
    shapes: [
    [
      "path",
      {
        "d": "m7 20 5-5 5 5",
      },
    ],
    [
      "path",
      {
        "d": "m7 4 5 5 5-5",
      },
    ],
    ],
  },
  "ChevronsUpDown": {
    // lucide/ChevronsUpDown — inks 10.0x16.0 of 24
    shapes: [
    [
      "path",
      {
        "d": "m7 15 5 5 5-5",
      },
    ],
    [
      "path",
      {
        "d": "m7 9 5-5 5 5",
      },
    ],
    ],
  },
  "Circle": {
    // lucide/Circle — inks 20.0x20.0 of 24
    shapes: [
    [
      "circle",
      {
        "cx": "12",
        "cy": "12",
        "r": "10",
      },
    ],
    ],
  },
  "Code": {
    // foundations/code-2, fitted ×0.909 — inks 18.2x14.5 of 24
    shapes: [
    [
      "path",
      {
        "d": "M17.4545 15.6364L21.0909 12L17.4545 8.3636",
      },
    ],
    [
      "path",
      {
        "d": "M6.5455 8.3636L2.9091 12L6.5455 15.6364",
      },
    ],
    [
      "path",
      {
        "d": "M14.2727 4.7273L9.7273 19.2727",
      },
    ],
    ],
  },
  "Component": {
    // lucide/Component — inks 20.0x20.0 of 24
    shapes: [
    [
      "path",
      {
        "d": "M15.536 11.293a1 1 0 0 0 0 1.414l2.376 2.377a1 1 0 0 0 1.414 0l2.377-2.377a1 1 0 0 0 0-1.414l-2.377-2.377a1 1 0 0 0-1.414 0z",
      },
    ],
    [
      "path",
      {
        "d": "M2.297 11.293a1 1 0 0 0 0 1.414l2.377 2.377a1 1 0 0 0 1.414 0l2.377-2.377a1 1 0 0 0 0-1.414L6.088 8.916a1 1 0 0 0-1.414 0z",
      },
    ],
    [
      "path",
      {
        "d": "M8.916 17.912a1 1 0 0 0 0 1.415l2.377 2.376a1 1 0 0 0 1.414 0l2.377-2.376a1 1 0 0 0 0-1.415l-2.377-2.376a1 1 0 0 0-1.414 0z",
      },
    ],
    [
      "path",
      {
        "d": "M8.916 4.674a1 1 0 0 0 0 1.414l2.377 2.376a1 1 0 0 0 1.414 0l2.377-2.376a1 1 0 0 0 0-1.414l-2.377-2.377a1 1 0 0 0-1.414 0z",
      },
    ],
    ],
  },
  "Constrain": {
    // lucide/Scaling — inks 16.2x16.2 of 24
    shapes: [
    [
      "path",
      {
        "d": "M12 3.9L5.7 3.9A1.8 1.8 0 0 0 3.9 5.7L3.9 18.3A1.8 1.8 0 0 0 5.7 20.1L18.3 20.1A1.8 1.8 0 0 0 20.1 18.3L20.1 12",
      },
    ],
    [
      "path",
      {
        "d": "M13.8 14.7L9.3 14.7L9.3 10.2",
      },
    ],
    [
      "path",
      {
        "d": "M15.6 3.9L20.1 3.9L20.1 8.4",
      },
    ],
    [
      "path",
      {
        "d": "M20.1 3.9L9.3 14.7",
      },
    ],
    ],
  },
  "Copy": {
    // foundations/copy, fitted ×0.909 — inks 16.4x20.0 of 24
    shapes: [
    [
      "path",
      {
        "d": "M19.3818 5.37L16.8127 2.7991A2.7509 2.7509 0 0 0 14.8818 2L10.1845 2A2.7336 2.7336 0 0 0 7.4545 4.7309L7.4545 5.6364L6.5491 5.6364A2.7336 2.7336 0 0 0 3.8182 8.3673L3.8182 19.2691A2.7336 2.7336 0 0 0 6.5491 22L13.8145 22A2.7336 2.7336 0 0 0 16.5455 19.2691L16.5455 18.3636L17.4509 18.3636A2.7336 2.7336 0 0 0 20.1818 15.6327L20.1818 7.3A2.7091 2.7091 0 0 0 19.3818 5.37zM17.9873 6.5455L15.6364 6.5464L15.6364 4.1945L17.9873 6.5455zM14.7273 19.2691C14.7273 19.7727 14.3182 20.1818 13.8145 20.1818L6.5491 20.1818C6.0455 20.1818 5.6364 19.7727 5.6364 19.2691L5.6364 8.3673C5.6364 7.8636 6.0455 7.4545 6.5491 7.4545L7.4545 7.4545L7.4545 15.6327A2.7336 2.7336 0 0 0 10.1855 18.3636L14.7273 18.3636L14.7273 19.2691zM17.4509 16.5455L10.1855 16.5455C9.6818 16.5455 9.2727 16.1364 9.2727 15.6327L9.2727 4.7309C9.2727 4.2273 9.6818 3.8182 10.1855 3.8182L13.8182 3.8182L13.8182 6.5464A1.8182 1.8182 0 0 0 15.6355 8.3636L18.3636 8.3636L18.3636 15.6327C18.3636 16.1364 17.9545 16.5455 17.4509 16.5455z",
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    ],
  },
  "CornerRadius": {
    // native — inks 18.0x18.0 of 24
    shapes: [
    [
      "path",
      {
        "d": "M4.5 21v-6a10.5 10.5 0 0 1 10.5 -10.5h6v1.5h-6a9 9 0 0 0 -9 9v6z",
        "fill-rule": "evenodd",
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    [
      "rect",
      {
        "x": 3,
        "y": 3,
        "width": 3,
        "height": 3,
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    [
      "rect",
      {
        "x": 18,
        "y": 18,
        "width": 3,
        "height": 3,
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    ],
  },
  "Cursor": {
    // native — inks 17.9x17.9 of 24
    shapes: [
    [
      "path",
      {
        "d": "M2.9458701710094917 4.500172213613091A1.2000000000000002 1.2000000000000002 0 0 1 4.500172213613091 2.9458701710094917L20.224904688491698 9.08655037105333A0.8999999999999999 0.8999999999999999 0 0 1 20.192392687617 10.775218664777976L14.231081834853054 12.842447428236444A2.25 2.25 0 0 0 12.842447428236444 14.231081834853054L10.775218664777976 20.192392687617A0.8999999999999999 0.8999999999999999 0 0 1 9.08655037105333 20.224904688491698L2.9458701710094917 4.500172213613091zM6.473293579598364 7.347588478562889A0.675 0.675 0 0 1 7.347588478562889 6.473293579598364L14.856257773356079 9.405511150922711A0.44999999999999996 0.44999999999999996 0 0 1 14.84000177291873 10.249845297785035L13.150211599969762 10.835820922275406A3.75 3.75 0 0 0 10.835820922275406 13.150211599969762L10.249845297785035 14.84000177291873A0.44999999999999996 0.44999999999999996 0 0 1 9.405511150922711 14.856257773356079L6.473293579598364 7.347588478562889z",
        "fill-rule": "evenodd",
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    ],
    // filled counterpart — inks 17.9x17.9 of 24
    filled: [
    [
      "path",
      {
        "d": "M2.9458701710094917 4.500172213613091A1.2000000000000002 1.2000000000000002 0 0 1 4.500172213613091 2.9458701710094917L20.224904688491698 9.08655037105333A0.8999999999999999 0.8999999999999999 0 0 1 20.192392687617 10.775218664777976L14.231081834853054 12.842447428236444A2.25 2.25 0 0 0 12.842447428236444 14.231081834853054L10.775218664777976 20.192392687617A0.8999999999999999 0.8999999999999999 0 0 1 9.08655037105333 20.224904688491698L2.9458701710094917 4.500172213613091z",
        "fill-rule": "evenodd",
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    ],
  },
  "ExternalLink": {
    // foundations/external-link, fitted ×0.909 — inks 20.0x20.0 of 24
    shapes: [
    [
      "path",
      {
        "d": "M21.0909 13.8182A0.9091 0.9091 0 0 0 20.1818 14.7273L20.1818 18.3636A1.82 1.82 0 0 1 18.3636 20.1818L5.6364 20.1818A1.82 1.82 0 0 1 3.8182 18.3636L3.8182 5.6364A1.82 1.82 0 0 1 5.6364 3.8182L9.2727 3.8182A0.9091 0.9091 0 0 0 9.2727 2L5.6364 2A3.64 3.64 0 0 0 2 5.6364L2 18.3636A3.64 3.64 0 0 0 5.6364 22L18.3636 22A3.64 3.64 0 0 0 22 18.3636L22 14.7273A0.9091 0.9091 0 0 0 21.0909 13.8182zM21.0909 2L14.7273 2A0.9091 0.9091 0 0 0 14.7273 3.8182L18.8964 3.8182L7.7209 14.9936A0.9091 0.9091 0 1 0 9.0064 16.2791L20.1818 5.1036L20.1818 9.2727A0.9091 0.9091 0 0 0 22 9.2727L22 2.9091A0.9091 0.9091 0 0 0 21.0909 2z",
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    ],
  },
  "Eye": {
    // lucide/Eye — inks 20.0x14.0 of 24
    shapes: [
    [
      "path",
      {
        "d": "M2.062 12.348a1 1 0 0 1 0-.696 10.75 10.75 0 0 1 19.876 0 1 1 0 0 1 0 .696 10.75 10.75 0 0 1-19.876 0",
      },
    ],
    [
      "circle",
      {
        "cx": "12",
        "cy": "12",
        "r": "3",
      },
    ],
    ],
  },
  "EyeOff": {
    // lucide/EyeOff — inks 20.0x20.0 of 24
    shapes: [
    [
      "path",
      {
        "d": "M10.733 5.076a10.744 10.744 0 0 1 11.205 6.575 1 1 0 0 1 0 .696 10.747 10.747 0 0 1-1.444 2.49",
      },
    ],
    [
      "path",
      {
        "d": "M14.084 14.158a3 3 0 0 1-4.242-4.242",
      },
    ],
    [
      "path",
      {
        "d": "M17.479 17.499a10.75 10.75 0 0 1-15.417-5.151 1 1 0 0 1 0-.696 10.75 10.75 0 0 1 4.446-5.143",
      },
    ],
    [
      "path",
      {
        "d": "m2 2 20 20",
      },
    ],
    ],
  },
  "EyeOpen": {
    // lucide/Eye — inks 20.0x14.0 of 24
    shapes: [
    [
      "path",
      {
        "d": "M2.062 12.348a1 1 0 0 1 0-.696 10.75 10.75 0 0 1 19.876 0 1 1 0 0 1 0 .696 10.75 10.75 0 0 1-19.876 0",
      },
    ],
    [
      "circle",
      {
        "cx": "12",
        "cy": "12",
        "r": "3",
      },
    ],
    ],
  },
  "FlowHorizontal": {
    // native — inks 18.0x18.0 of 24
    shapes: [
    [
      "path",
      {
        "d": "M5.25 3h3a2.25 2.25 0 0 1 2.25 2.25v3a2.25 2.25 0 0 1 -2.25 2.25h-3a2.25 2.25 0 0 1 -2.25 -2.25v-3a2.25 2.25 0 0 1 2.25 -2.25zM5.25 4.5h3a0.75 0.75 0 0 1 0.75 0.75v3a0.75 0.75 0 0 1 -0.75 0.75h-3a0.75 0.75 0 0 1 -0.75 -0.75v-3a0.75 0.75 0 0 1 0.75 -0.75z",
        "fill-rule": "evenodd",
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    [
      "path",
      {
        "d": "M15.75 3h3a2.25 2.25 0 0 1 2.25 2.25v3a2.25 2.25 0 0 1 -2.25 2.25h-3a2.25 2.25 0 0 1 -2.25 -2.25v-3a2.25 2.25 0 0 1 2.25 -2.25zM15.75 4.5h3a0.75 0.75 0 0 1 0.75 0.75v3a0.75 0.75 0 0 1 -0.75 0.75h-3a0.75 0.75 0 0 1 -0.75 -0.75v-3a0.75 0.75 0 0 1 0.75 -0.75z",
        "fill-rule": "evenodd",
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    [
      "rect",
      {
        "x": 3,
        "y": 16.5,
        "width": 16.5,
        "height": 1.5,
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    [
      "path",
      {
        "d": "M17.25 13.5L21 17.25L17.25 21L15.149999999999999 21L18.9 17.25L15.149999999999999 13.5z",
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    ],
  },
  "FlowNone": {
    // native — inks 18.0x18.0 of 24
    shapes: [
    [
      "path",
      {
        "d": "M5.25 3h3a2.25 2.25 0 0 1 2.25 2.25v3a2.25 2.25 0 0 1 -2.25 2.25h-3a2.25 2.25 0 0 1 -2.25 -2.25v-3a2.25 2.25 0 0 1 2.25 -2.25zM5.25 4.5h3a0.75 0.75 0 0 1 0.75 0.75v3a0.75 0.75 0 0 1 -0.75 0.75h-3a0.75 0.75 0 0 1 -0.75 -0.75v-3a0.75 0.75 0 0 1 0.75 -0.75z",
        "fill-rule": "evenodd",
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    [
      "path",
      {
        "d": "M15.75 9h3a2.25 2.25 0 0 1 2.25 2.25v3a2.25 2.25 0 0 1 -2.25 2.25h-3a2.25 2.25 0 0 1 -2.25 -2.25v-3a2.25 2.25 0 0 1 2.25 -2.25zM15.75 10.5h3a0.75 0.75 0 0 1 0.75 0.75v3a0.75 0.75 0 0 1 -0.75 0.75h-3a0.75 0.75 0 0 1 -0.75 -0.75v-3a0.75 0.75 0 0 1 0.75 -0.75z",
        "fill-rule": "evenodd",
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    [
      "path",
      {
        "d": "M5.25 13.5h3a2.25 2.25 0 0 1 2.25 2.25v3a2.25 2.25 0 0 1 -2.25 2.25h-3a2.25 2.25 0 0 1 -2.25 -2.25v-3a2.25 2.25 0 0 1 2.25 -2.25zM5.25 15h3a0.75 0.75 0 0 1 0.75 0.75v3a0.75 0.75 0 0 1 -0.75 0.75h-3a0.75 0.75 0 0 1 -0.75 -0.75v-3a0.75 0.75 0 0 1 0.75 -0.75z",
        "fill-rule": "evenodd",
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    ],
  },
  "FlowVertical": {
    // native — inks 18.0x18.0 of 24
    shapes: [
    [
      "path",
      {
        "d": "M5.25 3h3a2.25 2.25 0 0 1 2.25 2.25v3a2.25 2.25 0 0 1 -2.25 2.25h-3a2.25 2.25 0 0 1 -2.25 -2.25v-3a2.25 2.25 0 0 1 2.25 -2.25zM5.25 4.5h3a0.75 0.75 0 0 1 0.75 0.75v3a0.75 0.75 0 0 1 -0.75 0.75h-3a0.75 0.75 0 0 1 -0.75 -0.75v-3a0.75 0.75 0 0 1 0.75 -0.75z",
        "fill-rule": "evenodd",
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    [
      "path",
      {
        "d": "M5.25 13.5h3a2.25 2.25 0 0 1 2.25 2.25v3a2.25 2.25 0 0 1 -2.25 2.25h-3a2.25 2.25 0 0 1 -2.25 -2.25v-3a2.25 2.25 0 0 1 2.25 -2.25zM5.25 15h3a0.75 0.75 0 0 1 0.75 0.75v3a0.75 0.75 0 0 1 -0.75 0.75h-3a0.75 0.75 0 0 1 -0.75 -0.75v-3a0.75 0.75 0 0 1 0.75 -0.75z",
        "fill-rule": "evenodd",
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    [
      "rect",
      {
        "x": 16.5,
        "y": 3,
        "width": 1.5,
        "height": 16.5,
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    [
      "path",
      {
        "d": "M13.5 17.25L17.25 21L21 17.25L21 15.149999999999999L17.25 18.9L13.5 15.149999999999999z",
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    ],
  },
  "FlowWrap": {
    // native — inks 18.0x18.0 of 24
    shapes: [
    [
      "path",
      {
        "d": "M5.25 3h3a2.25 2.25 0 0 1 2.25 2.25v3a2.25 2.25 0 0 1 -2.25 2.25h-3a2.25 2.25 0 0 1 -2.25 -2.25v-3a2.25 2.25 0 0 1 2.25 -2.25zM5.25 4.5h3a0.75 0.75 0 0 1 0.75 0.75v3a0.75 0.75 0 0 1 -0.75 0.75h-3a0.75 0.75 0 0 1 -0.75 -0.75v-3a0.75 0.75 0 0 1 0.75 -0.75z",
        "fill-rule": "evenodd",
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    [
      "path",
      {
        "d": "M15.75 3h3a2.25 2.25 0 0 1 2.25 2.25v3a2.25 2.25 0 0 1 -2.25 2.25h-3a2.25 2.25 0 0 1 -2.25 -2.25v-3a2.25 2.25 0 0 1 2.25 -2.25zM15.75 4.5h3a0.75 0.75 0 0 1 0.75 0.75v3a0.75 0.75 0 0 1 -0.75 0.75h-3a0.75 0.75 0 0 1 -0.75 -0.75v-3a0.75 0.75 0 0 1 0.75 -0.75z",
        "fill-rule": "evenodd",
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    [
      "path",
      {
        "d": "M5.25 13.5h3a2.25 2.25 0 0 1 2.25 2.25v3a2.25 2.25 0 0 1 -2.25 2.25h-3a2.25 2.25 0 0 1 -2.25 -2.25v-3a2.25 2.25 0 0 1 2.25 -2.25zM5.25 15h3a0.75 0.75 0 0 1 0.75 0.75v3a0.75 0.75 0 0 1 -0.75 0.75h-3a0.75 0.75 0 0 1 -0.75 -0.75v-3a0.75 0.75 0 0 1 0.75 -0.75z",
        "fill-rule": "evenodd",
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    [
      "path",
      {
        "d": "M15.75 13.5h3a2.25 2.25 0 0 1 2.25 2.25v3a2.25 2.25 0 0 1 -2.25 2.25h-3a2.25 2.25 0 0 1 -2.25 -2.25v-3a2.25 2.25 0 0 1 2.25 -2.25zM15.75 15h3a0.75 0.75 0 0 1 0.75 0.75v3a0.75 0.75 0 0 1 -0.75 0.75h-3a0.75 0.75 0 0 1 -0.75 -0.75v-3a0.75 0.75 0 0 1 0.75 -0.75z",
        "fill-rule": "evenodd",
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    ],
  },
  "GapColumn": {
    // native — inks 18.0x15.0 of 24
    shapes: [
    [
      "rect",
      {
        "x": 3,
        "y": 4.5,
        "width": 3,
        "height": 15,
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    [
      "rect",
      {
        "x": 18,
        "y": 4.5,
        "width": 3,
        "height": 15,
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    [
      "rect",
      {
        "x": 9,
        "y": 10.5,
        "width": 1.5,
        "height": 3,
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    [
      "rect",
      {
        "x": 13.5,
        "y": 10.5,
        "width": 1.5,
        "height": 3,
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    ],
  },
  "GapRow": {
    // native — inks 15.0x18.0 of 24
    shapes: [
    [
      "rect",
      {
        "x": 4.5,
        "y": 3,
        "width": 15,
        "height": 3,
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    [
      "rect",
      {
        "x": 4.5,
        "y": 18,
        "width": 15,
        "height": 3,
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    [
      "rect",
      {
        "x": 10.5,
        "y": 9,
        "width": 3,
        "height": 1.5,
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    [
      "rect",
      {
        "x": 10.5,
        "y": 13.5,
        "width": 3,
        "height": 1.5,
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    ],
  },
  "Grid2x2": {
    // lucide/Grid2x2 — inks 16.2x16.2 of 24
    shapes: [
    [
      "path",
      {
        "d": "M12 3.9L12 20.1",
      },
    ],
    [
      "path",
      {
        "d": "M3.9 12L20.1 12",
      },
    ],
    [
      "rect",
      {
        "x": 3.9000000000000004,
        "y": 3.9000000000000004,
        "width": 16.200000000000003,
        "height": 16.200000000000003,
        "rx": 1.8,
      },
    ],
    ],
    // filled counterpart — inks 18.0x18.0 of 24
    filled: [
    [
      "path",
      {
        "d": "M4.5 3h5a1.5 1.5 0 0 1 1.5 1.5v5a1.5 1.5 0 0 1 -1.5 1.5h-5a1.5 1.5 0 0 1 -1.5 -1.5v-5a1.5 1.5 0 0 1 1.5 -1.5zM4.5 13h5a1.5 1.5 0 0 1 1.5 1.5v5a1.5 1.5 0 0 1 -1.5 1.5h-5a1.5 1.5 0 0 1 -1.5 -1.5v-5a1.5 1.5 0 0 1 1.5 -1.5zM14.5 3h5a1.5 1.5 0 0 1 1.5 1.5v5a1.5 1.5 0 0 1 -1.5 1.5h-5a1.5 1.5 0 0 1 -1.5 -1.5v-5a1.5 1.5 0 0 1 1.5 -1.5zM14.5 13h5a1.5 1.5 0 0 1 1.5 1.5v5a1.5 1.5 0 0 1 -1.5 1.5h-5a1.5 1.5 0 0 1 -1.5 -1.5v-5a1.5 1.5 0 0 1 1.5 -1.5z",
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    ],
  },
  "Image": {
    // foundations/image, fitted ×0.909 — inks 20.0x20.0 of 24
    shapes: [
    [
      "circle",
      {
        "cx": 7.0012727272727275,
        "cy": 7.000218181818182,
        "r": 1.363190909090909,
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    [
      "path",
      {
        "d": "M17.8591 2L6.1455 2A4.15 4.15 0 0 0 2 6.1455L2 17.8582A4.15 4.15 0 0 0 6.1455 22.0027L17.8591 22.0027A4.15 4.15 0 0 0 22.0045 17.8582L22.0045 6.1455A4.15 4.15 0 0 0 17.8591 2zM20.1864 17.8582A2.3291 2.3291 0 0 1 17.8591 20.1845L6.1455 20.1845C5.0218 20.1845 4.0818 19.3845 3.8655 18.3236L7.0318 15.1573L9.5236 17.6482A1.7364 1.7364 0 0 0 11.9773 17.6482L16.9482 12.6782L20.1864 15.9173L20.1864 17.8582zM20.1864 13.3455L18.1745 11.3336A1.7218 1.7218 0 0 0 16.9482 10.8255L16.9464 10.8255C16.4827 10.8255 16.0482 11.0073 15.7227 11.3336L10.7509 16.3036L8.2582 13.8109A1.7364 1.7364 0 0 0 5.8064 13.8118L3.8182 15.8L3.8182 6.1455A2.33 2.33 0 0 1 6.1455 3.8182L17.8591 3.8182A2.33 2.33 0 0 1 20.1864 6.1455L20.1864 13.3455z",
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    ],
  },
  "ListChecks": {
    // foundations/list-checks, fitted ×0.909 — inks 20.0x20.0 of 24
    shapes: [
    [
      "path",
      {
        "d": "M7 15.6381C6.4975 15.6381 6.0909 16.0447 6.0909 16.5472S6.4975 17.4563 7 17.4563L14.2736 17.4563C14.7761 17.4563 15.1827 17.0497 15.1827 16.5472S14.7761 15.6381 14.2736 15.6381L7 15.6381zM17.9082 12.0018C17.9082 11.4993 17.5016 11.0927 16.9991 11.0927L7 11.0927C6.4975 11.0927 6.0909 11.4993 6.0909 12.0018S6.4975 12.9109 7 12.9109L16.9991 12.9109C17.5016 12.9109 17.9082 12.5043 17.9082 12.0018zM21.0909 7.1358C20.5884 7.1358 20.1818 7.5424 20.1818 8.0449L20.1818 18.3636C20.1818 19.3659 19.3659 20.1818 18.3636 20.1818L5.6364 20.1818C4.6341 20.1818 3.8182 19.3659 3.8182 18.3636L3.8182 5.6364C3.8182 4.6341 4.6341 3.8182 5.6364 3.8182L11.7053 3.8182C12.2077 3.8182 12.6143 3.4116 12.6143 2.9091S12.2077 2 11.7053 2L5.6364 2C3.6309 2 2 3.6309 2 5.6364L2 18.3636C2 20.3691 3.6309 22 5.6364 22L18.3636 22C20.3691 22 22 20.3691 22 18.3636L22 8.0449C22 7.5424 21.5934 7.1358 21.0909 7.1358zM7 6.5472C6.4975 6.5472 6.0909 6.9547 6.0909 7.4563C6.0909 7.9588 6.4984 8.3654 7 8.3654L12.1083 8.3636C12.6108 8.3636 13.0174 7.9561 13.0174 7.4545C13.0174 6.9521 12.6099 6.5455 12.1083 6.5455L7 6.5472zM16.2551 7.7449C16.4327 7.9224 16.6653 8.0112 16.8979 8.0112S17.3631 7.9224 17.5407 7.7449L21.7337 3.5519C22.0888 3.1967 22.0888 2.6215 21.7337 2.2663S20.8033 1.9112 20.4481 2.2663L16.8979 5.8166L15.37 4.2896C15.0149 3.9345 14.4396 3.9345 14.0845 4.2896S13.7294 5.22 14.0845 5.5751L16.2552 7.7449z",
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    ],
  },
  "Lock": {
    // foundations/lock, fitted ×0.909 — inks 13.3x18.2 of 24
    shapes: [
    [
      "path",
      {
        "d": "M7.1909 9.7773L16.81 9.7773A1.8582 1.8582 0 0 1 18.6682 11.6355L18.6682 19.2327A1.8582 1.8582 0 0 1 16.8109 21.09L7.1909 21.09A1.8582 1.8582 0 0 1 5.3327 19.2318L5.3327 11.6364A1.8582 1.8582 0 0 1 7.1909 9.7773zM8.1636 9.7773L8.1636 6.7473A3.8382 3.8382 0 0 1 15.84 6.7473L15.84 9.7773",
      },
    ],
    ],
  },
  "LockOpen": {
    // foundations/lock, fitted ×0.909 — inks 13.3x18.2 of 24
    shapes: [
    [
      "path",
      {
        "d": "M7.1909 9.7773L16.81 9.7773A1.8582 1.8582 0 0 1 18.6682 11.6355L18.6682 19.2327A1.8582 1.8582 0 0 1 16.8109 21.09L7.1909 21.09A1.8582 1.8582 0 0 1 5.3327 19.2318L5.3327 11.6364A1.8582 1.8582 0 0 1 7.1909 9.7773zM8.1636 9.7773L8.1636 6.7473A3.8382 3.8382 0 0 1 15.7627 5.98",
      },
    ],
    ],
  },
  "MessageSquare": {
    // foundations/message-square — inks 15.6x15.6 of 24
    shapes: [
    [
      "path",
      {
        "d": "M18.7517 15.9062A7.7945 7.7945 0 1 0 15.9515 18.7259L19.8 19.8z",
      },
    ],
    ],
  },
  "Minimize": {
    // lucide/Minimize — inks 18.0x18.0 of 24
    shapes: [
    [
      "path",
      {
        "d": "M8 3v3a2 2 0 0 1-2 2H3",
      },
    ],
    [
      "path",
      {
        "d": "M21 8h-3a2 2 0 0 1-2-2V3",
      },
    ],
    [
      "path",
      {
        "d": "M3 16h3a2 2 0 0 1 2 2v3",
      },
    ],
    [
      "path",
      {
        "d": "M16 21v-3a2 2 0 0 1 2-2h3",
      },
    ],
    ],
  },
  "Minus": {
    // lucide/Minus — inks 14.0x0.0 of 24
    shapes: [
    [
      "path",
      {
        "d": "M5 12h14",
      },
    ],
    ],
  },
  "Moon": {
    // lucide/Moon — inks 18.0x18.0 of 24
    shapes: [
    [
      "path",
      {
        "d": "M20.985 12.486a9 9 0 1 1-9.473-9.472c.405-.022.617.46.402.803a6 6 0 0 0 8.268 8.268c.344-.215.825-.004.803.401",
      },
    ],
    ],
  },
  "Opacity": {
    // native — inks 18.0x18.0 of 24
    shapes: [
    [
      "path",
      {
        "d": "M3 3h18v18h-18zM4.5 4.5h15v15h-15z",
        "fill-rule": "evenodd",
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    [
      "rect",
      {
        "x": 4.5,
        "y": 4.5,
        "width": 7.5,
        "height": 7.5,
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    [
      "rect",
      {
        "x": 12,
        "y": 12,
        "width": 7.5,
        "height": 7.5,
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    ],
  },
  "PadBottom": {
    // native — inks 18.0x18.0 of 24
    shapes: [
    [
      "path",
      {
        "d": "M3 3h18v18h-18zM4.5 4.5h15v15h-15z",
        "fill-rule": "evenodd",
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    [
      "rect",
      {
        "x": 3,
        "y": 18,
        "width": 18,
        "height": 3,
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    ],
  },
  "PadLeft": {
    // native — inks 18.0x18.0 of 24
    shapes: [
    [
      "path",
      {
        "d": "M3 3h18v18h-18zM4.5 4.5h15v15h-15z",
        "fill-rule": "evenodd",
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    [
      "rect",
      {
        "x": 3,
        "y": 3,
        "width": 3,
        "height": 18,
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    ],
  },
  "PadRight": {
    // native — inks 18.0x18.0 of 24
    shapes: [
    [
      "path",
      {
        "d": "M3 3h18v18h-18zM4.5 4.5h15v15h-15z",
        "fill-rule": "evenodd",
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    [
      "rect",
      {
        "x": 18,
        "y": 3,
        "width": 3,
        "height": 18,
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    ],
  },
  "PadTop": {
    // native — inks 18.0x18.0 of 24
    shapes: [
    [
      "path",
      {
        "d": "M3 3h18v18h-18zM4.5 4.5h15v15h-15z",
        "fill-rule": "evenodd",
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    [
      "rect",
      {
        "x": 3,
        "y": 3,
        "width": 18,
        "height": 3,
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    ],
  },
  "PanelLeft": {
    // native — inks 18.0x18.0 of 24
    shapes: [
    [
      "path",
      {
        "d": "M6.75 3h10.5a3.75 3.75 0 0 1 3.75 3.75v10.5a3.75 3.75 0 0 1 -3.75 3.75h-10.5a3.75 3.75 0 0 1 -3.75 -3.75v-10.5a3.75 3.75 0 0 1 3.75 -3.75zM6.75 5.25h10.5a1.5 1.5 0 0 1 1.5 1.5v10.5a1.5 1.5 0 0 1 -1.5 1.5h-10.5a1.5 1.5 0 0 1 -1.5 -1.5v-10.5a1.5 1.5 0 0 1 1.5 -1.5z",
        "fill-rule": "evenodd",
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    [
      "rect",
      {
        "x": 9,
        "y": 5.25,
        "width": 2.25,
        "height": 13.5,
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    ],
    // filled counterpart — inks 18.0x18.0 of 24
    filled: [
    [
      "path",
      {
        "d": "M6.75 3h10.5a3.75 3.75 0 0 1 3.75 3.75v10.5a3.75 3.75 0 0 1 -3.75 3.75h-10.5a3.75 3.75 0 0 1 -3.75 -3.75v-10.5a3.75 3.75 0 0 1 3.75 -3.75zM6.75 5.25h10.5a1.5 1.5 0 0 1 1.5 1.5v10.5a1.5 1.5 0 0 1 -1.5 1.5h-10.5a1.5 1.5 0 0 1 -1.5 -1.5v-10.5a1.5 1.5 0 0 1 1.5 -1.5z",
        "fill-rule": "evenodd",
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    [
      "path",
      {
        "d": "M6.75 5.25h4.5v13.5h-4.5a1.5 1.5 0 0 1 -1.5 -1.5v-10.5a1.5 1.5 0 0 1 1.5 -1.5z",
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    ],
  },
  "PanelRight": {
    // native — inks 18.0x18.0 of 24
    shapes: [
    [
      "path",
      {
        "d": "M6.75 3h10.5a3.75 3.75 0 0 1 3.75 3.75v10.5a3.75 3.75 0 0 1 -3.75 3.75h-10.5a3.75 3.75 0 0 1 -3.75 -3.75v-10.5a3.75 3.75 0 0 1 3.75 -3.75zM6.75 5.25h10.5a1.5 1.5 0 0 1 1.5 1.5v10.5a1.5 1.5 0 0 1 -1.5 1.5h-10.5a1.5 1.5 0 0 1 -1.5 -1.5v-10.5a1.5 1.5 0 0 1 1.5 -1.5z",
        "fill-rule": "evenodd",
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    [
      "rect",
      {
        "x": 12.75,
        "y": 5.25,
        "width": 2.25,
        "height": 13.5,
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    ],
    // filled counterpart — inks 18.0x18.0 of 24
    filled: [
    [
      "path",
      {
        "d": "M6.75 3h10.5a3.75 3.75 0 0 1 3.75 3.75v10.5a3.75 3.75 0 0 1 -3.75 3.75h-10.5a3.75 3.75 0 0 1 -3.75 -3.75v-10.5a3.75 3.75 0 0 1 3.75 -3.75zM6.75 5.25h10.5a1.5 1.5 0 0 1 1.5 1.5v10.5a1.5 1.5 0 0 1 -1.5 1.5h-10.5a1.5 1.5 0 0 1 -1.5 -1.5v-10.5a1.5 1.5 0 0 1 1.5 -1.5z",
        "fill-rule": "evenodd",
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    [
      "path",
      {
        "d": "M12.75 5.25h4.5a1.5 1.5 0 0 1 1.5 1.5v10.5a1.5 1.5 0 0 1 -1.5 1.5h-4.5z",
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    ],
  },
  "Pencil": {
    // foundations/pencil, fitted ×0.909 — inks 18.2x18.2 of 24
    shapes: [
    [
      "path",
      {
        "d": "M6.7018 21.0909L2.9091 21.0909L2.9091 17.2982L16.81 3.3964A1.6645 1.6645 0 0 1 19.1645 3.3964L20.6036 4.8355A1.6645 1.6645 0 0 1 20.6036 7.19z",
      },
    ],
    [
      "path",
      {
        "d": "M14.744 5.463L18.537 9.256",
      },
    ],
    ],
  },
  "Play": {
    // foundations/play, fitted ×0.909 — inks 15.6x17.3 of 24
    shapes: [
    [
      "path",
      {
        "d": "M5.3309 20.3382A2.2191 2.2191 0 0 1 4.2218 18.4145L4.2218 5.5855A2.2218 2.2218 0 0 1 7.5555 3.6582L18.6664 10.0736A2.2218 2.2218 0 0 1 18.6664 13.9236L7.5555 20.3382A2.2236 2.2236 0 0 1 5.3309 20.3382z",
      },
    ],
    ],
  },
  "Plus": {
    // foundations/plus — inks 14.0x14.0 of 24
    shapes: [
    [
      "path",
      {
        "d": "M5 12h14",
      },
    ],
    [
      "path",
      {
        "d": "M12 5v14",
      },
    ],
    ],
  },
  "Search": {
    // foundations/search, fitted ×0.909 — inks 18.2x18.2 of 24
    shapes: [
    [
      "path",
      {
        "d": "M18.3636 10.6364A7.7273 7.7273 0 1 1 10.6364 2.9091A7.7273 7.7273 0 0 1 18.3636 10.6364z",
      },
    ],
    [
      "path",
      {
        "d": "M16.1008 16.1008L21.0909 21.0909",
      },
    ],
    ],
  },
  "Send": {
    // foundations/paper-plane-filled, fitted ×0.909 — inks 20.3x18.5 of 24
    shapes: [
    [
      "path",
      {
        "d": "M6.8682 12.4036L3.2927 8.9791A3.28 3.28 0 0 1 5.5664 3.33L19.2755 3.3527A3.28 3.28 0 0 1 22.0891 8.3082L15.0309 20.1791A3.28 3.28 0 0 1 9.0309 19.3045L7.7 14.0218L16.0664 9.2764A0.9091 0.9091 0 0 0 15.1691 7.6955L6.8682 12.4036z",
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    ],
  },
  "SpaceBetweenHorizontal": {
    // native — inks 18.0x18.0 of 24
    shapes: [
    [
      "rect",
      {
        "x": 3,
        "y": 3,
        "width": 3,
        "height": 18,
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    [
      "rect",
      {
        "x": 18,
        "y": 3,
        "width": 3,
        "height": 18,
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    [
      "rect",
      {
        "x": 9,
        "y": 10.5,
        "width": 6,
        "height": 3,
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    ],
  },
  "SpaceBetweenVertical": {
    // native — inks 18.0x18.0 of 24
    shapes: [
    [
      "rect",
      {
        "x": 3,
        "y": 3,
        "width": 18,
        "height": 3,
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    [
      "rect",
      {
        "x": 3,
        "y": 18,
        "width": 18,
        "height": 3,
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    [
      "rect",
      {
        "x": 10.5,
        "y": 9,
        "width": 3,
        "height": 6,
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    ],
  },
  "Sparkles": {
    // foundations/sparkles, fitted ×0.909 — inks 20.0x20.1 of 24
    shapes: [
    [
      "path",
      {
        "d": "M13.8255 6.2609C13.3991 6.2227 12.1409 5.9609 12.1409 5.9609A1.7391 1.7391 0 0 1 10.7345 4.5536S10.4718 3.2955 10.4345 2.87A0.87 0.87 0 1 0 8.6955 2.87C8.6573 3.2955 8.3945 4.5536 8.3945 4.5536A1.7391 1.7391 0 0 1 6.9882 5.96S5.73 6.2236 5.3036 6.26A0.87 0.87 0 0 0 5.3036 8C5.73 8.0373 6.9882 8.3 6.9882 8.3A1.7391 1.7391 0 0 1 8.3945 9.7073S8.6573 10.9655 8.6945 11.3909A0.87 0.87 0 1 0 10.4345 11.3909C10.4718 10.9655 10.7345 9.7073 10.7345 9.7073A1.7391 1.7391 0 0 1 12.1409 8.3009S13.3991 8.0373 13.8255 8A0.87 0.87 0 1 0 13.8255 6.2609zM21.13 14.1782C20.7691 14.1509 19.6973 13.9555 19.6973 13.9555A1.5945 1.5945 0 0 1 18.3682 12.6255S18.1727 11.5545 18.1445 11.1927A0.87 0.87 0 0 0 16.4055 11.1927C16.3782 11.5536 16.1873 12.6245 16.1873 12.6245A1.5945 1.5945 0 0 1 14.8509 13.9609S13.7809 14.1518 13.42 14.1791A0.87 0.87 0 0 0 13.42 15.9173C13.7809 15.9445 14.8518 16.1355 14.8518 16.1355A1.5945 1.5945 0 0 1 16.1882 17.4718S16.3791 18.5418 16.4064 18.9027A0.87 0.87 0 0 0 18.1445 18.9027C18.1727 18.5418 18.3682 17.4709 18.3682 17.4709A1.5945 1.5945 0 0 1 19.6973 16.1409S20.7691 15.9455 21.13 15.9173A0.87 0.87 0 0 0 21.13 14.1782zM9.7682 16.8118C9.4727 16.7936 8.5945 16.6664 8.5945 16.6664A1.4491 1.4491 0 0 1 7.3336 15.4055S7.2064 14.5273 7.1882 14.2318A0.87 0.87 0 0 0 5.4491 14.2318C5.4309 14.5273 5.3045 15.4055 5.3045 15.4055A1.4491 1.4491 0 0 1 4.0436 16.6664S3.1645 16.7936 2.87 16.8118A0.87 0.87 0 1 0 2.87 18.5509C3.1645 18.5691 4.0436 18.6955 4.0436 18.6955A1.4491 1.4491 0 0 1 5.3045 19.9564S5.4318 20.8355 5.45 21.13A0.87 0.87 0 1 0 7.1882 21.13C7.2064 20.8355 7.3336 19.9564 7.3336 19.9564A1.4491 1.4491 0 0 1 8.5945 18.6955S9.4727 18.5682 9.7673 18.55A0.87 0.87 0 1 0 9.7673 16.8118z",
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    ],
  },
  "Square": {
    // lucide/Square — inks 16.2x16.2 of 24
    shapes: [
    [
      "rect",
      {
        "width": 16.200000000000003,
        "height": 16.200000000000003,
        "x": 3.9000000000000004,
        "y": 3.9000000000000004,
        "rx": 1.8,
      },
    ],
    ],
  },
  "Sun": {
    // lucide/Sun — inks 18.0x18.0 of 24
    shapes: [
    [
      "circle",
      {
        "cx": 12,
        "cy": 12,
        "r": 3.6,
      },
    ],
    [
      "path",
      {
        "d": "M12 3L12 4.8",
      },
    ],
    [
      "path",
      {
        "d": "M12 19.2L12 21",
      },
    ],
    [
      "path",
      {
        "d": "M5.637 5.637L6.906 6.906",
      },
    ],
    [
      "path",
      {
        "d": "M17.094 17.094L18.363 18.363",
      },
    ],
    [
      "path",
      {
        "d": "M3 12L4.8 12",
      },
    ],
    [
      "path",
      {
        "d": "M19.2 12L21 12",
      },
    ],
    [
      "path",
      {
        "d": "M6.906 17.094L5.637 18.363",
      },
    ],
    [
      "path",
      {
        "d": "M18.363 5.637L17.094 6.906",
      },
    ],
    ],
  },
  "TextAlignBottom": {
    // native — inks 18.0x18.0 of 24
    shapes: [
    [
      "rect",
      {
        "x": 3,
        "y": 19.5,
        "width": 18,
        "height": 1.5,
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    [
      "rect",
      {
        "x": 10.5,
        "y": 3,
        "width": 1.5,
        "height": 15,
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    [
      "path",
      {
        "d": "M6.75 13.5L11.25 18L15.75 13.5L15.75 11.399999999999999L11.25 15.899999999999999L6.75 11.399999999999999z",
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    ],
  },
  "TextAlignCenter": {
    // native — inks 18.0x13.5 of 24
    shapes: [
    [
      "rect",
      {
        "x": 3,
        "y": 4.5,
        "width": 18,
        "height": 1.5,
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    [
      "rect",
      {
        "x": 6,
        "y": 10.5,
        "width": 12,
        "height": 1.5,
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    [
      "rect",
      {
        "x": 4.5,
        "y": 16.5,
        "width": 15,
        "height": 1.5,
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    ],
  },
  "TextAlignJustify": {
    // native — inks 18.0x13.5 of 24
    shapes: [
    [
      "rect",
      {
        "x": 3,
        "y": 4.5,
        "width": 18,
        "height": 1.5,
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    [
      "rect",
      {
        "x": 3,
        "y": 10.5,
        "width": 18,
        "height": 1.5,
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    [
      "rect",
      {
        "x": 3,
        "y": 16.5,
        "width": 18,
        "height": 1.5,
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    ],
  },
  "TextAlignLeft": {
    // native — inks 18.0x13.5 of 24
    shapes: [
    [
      "rect",
      {
        "x": 3,
        "y": 4.5,
        "width": 18,
        "height": 1.5,
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    [
      "rect",
      {
        "x": 3,
        "y": 10.5,
        "width": 12,
        "height": 1.5,
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    [
      "rect",
      {
        "x": 3,
        "y": 16.5,
        "width": 15,
        "height": 1.5,
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    ],
  },
  "TextAlignMiddle": {
    // native — inks 18.0x18.6 of 24
    shapes: [
    [
      "rect",
      {
        "x": 3,
        "y": 10.5,
        "width": 18,
        "height": 1.5,
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    [
      "rect",
      {
        "x": 10.5,
        "y": 3,
        "width": 1.5,
        "height": 6,
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    [
      "path",
      {
        "d": "M6.75 4.5L11.25 9L15.75 4.5L15.75 2.3999999999999995L11.25 6.8999999999999995L6.75 2.3999999999999995z",
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    [
      "rect",
      {
        "x": 10.5,
        "y": 15,
        "width": 1.5,
        "height": 6,
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    [
      "path",
      {
        "d": "M6.75 18L11.25 13.5L15.75 18L15.75 20.1L11.25 15.600000000000001L6.75 20.1z",
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    ],
  },
  "TextAlignRight": {
    // native — inks 18.0x13.5 of 24
    shapes: [
    [
      "rect",
      {
        "x": 3,
        "y": 4.5,
        "width": 18,
        "height": 1.5,
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    [
      "rect",
      {
        "x": 9,
        "y": 10.5,
        "width": 12,
        "height": 1.5,
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    [
      "rect",
      {
        "x": 6,
        "y": 16.5,
        "width": 15,
        "height": 1.5,
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    ],
  },
  "TextAlignTop": {
    // native — inks 18.0x18.0 of 24
    shapes: [
    [
      "rect",
      {
        "x": 3,
        "y": 3,
        "width": 18,
        "height": 1.5,
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    [
      "rect",
      {
        "x": 10.5,
        "y": 6,
        "width": 1.5,
        "height": 15,
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    [
      "path",
      {
        "d": "M6.75 10.5L11.25 6L15.75 10.5L15.75 12.600000000000001L11.25 8.100000000000001L6.75 12.600000000000001z",
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    ],
  },
  "ToolClose": {
    // native — inks 15.1x15.1 of 24
    shapes: [
    [
      "path",
      {
        "d": "M4.800000000000001 4.800000000000001A1.1249999999999998 1.1249999999999998 0 0 0 4.800000000000001 6.390990257669731L17.609009742330265 19.200000000000003A1.125 1.125 0 0 0 19.200000000000003 19.200000000000003L19.200000000000003 19.200000000000003A1.125 1.125 0 0 0 19.200000000000003 17.609009742330265L6.390990257669731 4.800000000000001A1.1249999999999998 1.1249999999999998 0 0 0 4.800000000000001 4.800000000000001L4.800000000000001 4.800000000000001z",
        "fill-rule": "evenodd",
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    [
      "path",
      {
        "d": "M4.800000000000001 19.200000000000003A1.1249999999999996 1.1249999999999996 0 0 0 6.390990257669731 19.200000000000003L19.200000000000003 6.390990257669731A1.1249999999999996 1.1249999999999996 0 0 0 19.200000000000003 4.800000000000001L19.200000000000003 4.799999999999999A1.125 1.125 0 0 0 17.60900974233027 4.800000000000001L4.800000000000001 17.60900974233027A1.125 1.125 0 0 0 4.799999999999999 19.200000000000003L4.800000000000001 19.200000000000003z",
        "fill-rule": "evenodd",
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    ],
  },
  "ToolRedo": {
    // native — inks 17.3x18.0 of 24
    shapes: [
    [
      "path",
      {
        "d": "M16.125 3L20.25 7.125L16.125 11.25L12.943019484660537 11.25L17.06801948466054 7.125L12.943019484660537 3z",
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    [
      "rect",
      {
        "x": 10.5,
        "y": 6,
        "width": 9,
        "height": 2.25,
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    [
      "path",
      {
        "d": "M10.5 21A7.5 7.5 0 0 1 10.5 6L10.5 8.25A5.25 5.25 0 0 0 10.5 18.75z",
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    [
      "rect",
      {
        "x": 10.5,
        "y": 18.75,
        "width": 4.5,
        "height": 2.25,
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    ],
  },
  "ToolUndo": {
    // native — inks 17.3x18.0 of 24
    shapes: [
    [
      "path",
      {
        "d": "M7.875 3L3.75 7.125L7.875 11.25L11.056980515339465 11.25L6.931980515339465 7.125L11.056980515339465 3z",
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    [
      "rect",
      {
        "x": 4.5,
        "y": 6,
        "width": 9,
        "height": 2.25,
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    [
      "path",
      {
        "d": "M13.5 6A7.5 7.5 0 0 1 13.5 21L13.5 18.75A5.25 5.25 0 0 0 13.5 8.25z",
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    [
      "rect",
      {
        "x": 9,
        "y": 18.75,
        "width": 4.5,
        "height": 2.25,
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    ],
  },
  "Trash": {
    // foundations/trash-2, fitted ×0.909 — inks 16.6x18.2 of 24
    shapes: [
    [
      "path",
      {
        "d": "M3.7054 5.3884L20.2946 5.3884",
      },
    ],
    [
      "path",
      {
        "d": "M9.1073 5.3882L9.1073 3.9427A1.0327 1.0327 0 0 1 10.14 2.9091L13.86 2.9091A1.0327 1.0327 0 0 1 14.8927 3.9418L14.8927 5.3882",
      },
    ],
    [
      "path",
      {
        "d": "M5.07 5.3882L6.8764 19.8245A1.4455 1.4455 0 0 0 8.3109 21.0909L15.6891 21.0909A1.4455 1.4455 0 0 0 17.1236 19.8245L18.93 5.3882",
      },
    ],
    ],
  },
  "Type": {
    // lucide/Type — inks 16.0x16.0 of 24
    shapes: [
    [
      "path",
      {
        "d": "M12 4v16",
      },
    ],
    [
      "path",
      {
        "d": "M4 7V5a1 1 0 0 1 1-1h14a1 1 0 0 1 1 1v2",
      },
    ],
    [
      "path",
      {
        "d": "M9 20h6",
      },
    ],
    ],
  },
  "WrapText": {
    // lucide/WrapText — inks 18.0x17.0 of 24
    shapes: [
    [
      "path",
      {
        "d": "m16 16-3 3 3 3",
      },
    ],
    [
      "path",
      {
        "d": "M3 12h14.5a1 1 0 0 1 0 7H13",
      },
    ],
    [
      "path",
      {
        "d": "M3 19h6",
      },
    ],
    [
      "path",
      {
        "d": "M3 5h18",
      },
    ],
    ],
  },
  "X": {
    // foundations/x, fitted ×0.909 — inks 16.4x16.4 of 24
    shapes: [
    [
      "path",
      {
        "d": "M13.2855 12L19.9155 5.37A0.9091 0.9091 0 1 0 18.63 4.0845L12 10.7145L5.37 4.0845A0.9091 0.9091 0 1 0 4.0845 5.37L10.7145 12L4.0845 18.63A0.9091 0.9091 0 1 0 5.37 19.9155L12 13.2855L18.63 19.9155A0.9064 0.9064 0 0 0 19.9155 19.9155A0.9091 0.9091 0 0 0 19.9155 18.63L13.2855 12z",
        "fill": "currentColor",
        "stroke": "none",
      },
    ],
    ],
  },
  "XSmall": {
    // lucide/X — inks 12.0x12.0 of 24
    shapes: [
    [
      "path",
      {
        "d": "M18 6 6 18",
      },
    ],
    [
      "path",
      {
        "d": "m6 6 12 12",
      },
    ],
    ],
  },
} as const satisfies Record<string, IconData>

export type IconName = keyof typeof ICONS

export const ICON_NAMES = Object.keys(ICONS) as IconName[]

/**
 * The glyphs authored on the native 16 lattice rather than taken from Lucide.
 *
 * Exported so the rung rule can be CHECKED rather than just written down: these
 * land on whole device pixels only at a size that is a multiple of 8, so they
 * may be drawn at `icon.action` (16) or `icon.feature` (24), never at marker
 * 12, inline 14, chrome 18 or header 20. `test/icon-cases.mjs` reads this list
 * and greps the source for a call that breaks it.
 *
 * A comment could not carry this. The mistake it prevents — reaching for
 * `tokens.icon.marker` because the text beside the glyph is 12px — is locally
 * reasonable every single time, and the result looks fine until it is set
 * beside a glyph drawn at 16.
 */
export const NATIVE_ICON_NAMES = ["AlignCenterHorizontal","AlignCenterVertical","AlignEndHorizontal","AlignEndVertical","AlignStartHorizontal","AlignStartVertical","ArrangeBack","ArrangeBackward","ArrangeForward","ArrangeFront","CornerRadius","Cursor","FlowHorizontal","FlowNone","FlowVertical","FlowWrap","GapColumn","GapRow","Opacity","PadBottom","PadLeft","PadRight","PadTop","PanelLeft","PanelRight","SpaceBetweenHorizontal","SpaceBetweenVertical","TextAlignBottom","TextAlignCenter","TextAlignJustify","TextAlignLeft","TextAlignMiddle","TextAlignRight","TextAlignTop","ToolClose","ToolRedo","ToolUndo"] as const satisfies readonly IconName[]

/** The rungs a native glyph renders crisply at — every multiple of 8 on the ramp. */
export const NATIVE_ICON_SIZES = [16, 24] as const satisfies readonly IconSize[]

const SVG_NS = "http://www.w3.org/2000/svg"

function build(node: IconNode): SVGElement {
  const [tag, attrs, children] = node
  const element = document.createElementNS(SVG_NS, tag)
  for (const [key, value] of Object.entries(attrs)) element.setAttribute(key, String(value))
  for (const child of children ?? []) element.append(build(child))
  return element
}

/**
 * Draw one glyph from its data.
 *
 * Exported so the host's own icon set — served by the loopback `/icons` route
 * and offered as variants in the inspector — is drawn by the same rules as
 * these. Two renderers would be two answers to "how big is a glyph", and only
 * one of them would be right.
 */
export function drawIcon(data: IconData, size: IconSize = 16, weight: IconWeight = "auto"): SVGSVGElement {
  const svg = document.createElementNS(SVG_NS, "svg")
  svg.setAttribute("width", String(size))
  svg.setAttribute("height", String(size))
  svg.setAttribute("viewBox", "0 0 24 24")
  // The fill is opt-in and the outline is what `auto` means: a flood reads only
  // on a closed silhouette, so a caller asks for it knowing which mark it holds.
  svg.setAttribute("fill", weight === "filled" ? "currentColor" : "none")
  svg.setAttribute("stroke", "currentColor")
  const stroke = STROKE_FOR_SIZE[size]
  svg.setAttribute("stroke-width", String(stroke))
  svg.style.setProperty(ICON_STROKE_VARIABLE, String(stroke))
  svg.setAttribute("stroke-linecap", "round")
  svg.setAttribute("stroke-linejoin", "round")
  svg.setAttribute(ICON_MARKER_ATTRIBUTE, "")
  svg.setAttribute("aria-hidden", "true")
  // The counterpart when the glyph has one, its own shapes otherwise. A mark
  // whose runs are all open floods to nothing, and a toggle drawing it would
  // report the same picture in both states.
  const shapes = weight === "filled" && data.filled ? data.filled : data.shapes
  for (const node of shapes) svg.append(build(node))
  return svg
}

/**
 * One glyph, sized and decorative.
 *
 * Colour comes from `currentColor`, never a token: the same mark is drawn on a
 * rest row, a hovered row and a filled selected row, and only the caller knows
 * which.
 */
export function icon(name: IconName, size: IconSize = 16, weight: IconWeight = "auto"): SVGSVGElement {
  const svg = drawIcon(ICONS[name], size, weight)
  /*
   * THE MARKER CARRIES THE NAME NOW, where it used to carry an empty string.
   *
   * Every rule that reads it is written `svg[data-de-glyph]`, which matches on
   * presence and is unaffected. What the value adds is the ability to say
   * something about ONE mark — and there is exactly one thing worth saying,
   * which is the optical correction for `Cursor` in `css/icons.ts`.
   *
   * Set here and not in `drawIcon`, because `drawIcon` also renders the HOST
   * app's own icons, whose names belong to a set this package did not author. A
   * rule written against one of ours must not be able to reach one of theirs.
   */
  svg.setAttribute(ICON_MARKER_ATTRIBUTE, name)
  return svg
}

/**
 * A glyph from the HOST's own icon set, which is a different set of rules.
 *
 * The app being edited ships its own icons, served by the loopback `/icons`
 * route so the inspector can offer one in place of another. Those are drawn the
 * way their author drew them: one weight, whatever grid and stroke they use,
 * nothing normalised. They must not be squeezed into the chrome's shape — this
 * editor does not get to decide that someone else's icon is a stroke family, or
 * to re-window a glyph it is about to write into their source. A second, smaller
 * renderer is the honest way to say that.
 */
export interface HostIconData {
  nodes: IconNode[]
  rootFill: string
  rootStroke?: string
}

export function drawHostIcon(data: HostIconData, size: IconSize = 16): SVGSVGElement {
  const svg = document.createElementNS(SVG_NS, "svg")
  svg.setAttribute("width", String(size))
  svg.setAttribute("height", String(size))
  svg.setAttribute("viewBox", "0 0 24 24")
  svg.setAttribute("fill", data.rootFill === "none" ? "none" : "currentColor")
  if (data.rootStroke) {
    svg.setAttribute("stroke", "currentColor")
    svg.setAttribute("stroke-width", "2")
    svg.setAttribute("stroke-linecap", "round")
    svg.setAttribute("stroke-linejoin", "round")
  }
  svg.setAttribute("aria-hidden", "true")
  for (const node of data.nodes) svg.append(build(node))
  return svg
}
